export type ErrorCode =
  | "INVALID_ARGUMENT"
  | "CAPABILITY_UNAVAILABLE"
  | "INVALID_PROJECT"
  | "SERIALIZATION_FAILED"
  | "IMPORT_FAILED"
  | "EXPORT_FAILED"
  | "RENDER_FAILED"
  | "PLUGIN_REJECTED"
  | "INTERNAL_ERROR";
