import type { ProjectTemplate } from "../TemplateTypes";
import { createInitialProject, updateProjectSettings } from "../../project/ProjectStore";

export const EmptySceneTemplate: ProjectTemplate = {
  id: "empty-scene",
  name: "Empty Scene",
  description: "Grid, default camera, default sky, no terrain or characters.",
  category: "starter",
  schemaVersion: 1,
  templateVersion: 1,
  preview: { accent: "#6aa7ff", icon: "empty", aspectRatio: "16:9", summary: "Generated MineMotion starter content" },
  dependencies: [],
  estimatedSizeBytes: 24000,
  license: "MineMotion-generated",
  attribution: "Generated by BlockMotion Studio; no Mojang/Microsoft assets included.",
  tags: ["builtin", "starter"],
  create(settings) {
    const project = createInitialProject(settings);
    return updateProjectSettings(
      {
        ...project,
        scene: {
          ...project.scene,
          characters: []
        }
      },
      {
        projectName: "Empty Scene",
        terrainPreset: "none"
      }
    );
  }
};

