import type { ProjectTemplate } from "../TemplateTypes";
import { createInitialProject, updateProjectSettings } from "../../project/ProjectStore";

export const FlatWorldTemplate: ProjectTemplate = {
  id: "flat-minecraft-world",
  name: "Flat Minecraft World",
  description: "Flat grass and dirt test world with one camera and light.",
  category: "starter",
  schemaVersion: 1,
  templateVersion: 1,
  preview: { accent: "#6aa7ff", icon: "world", aspectRatio: "16:9", summary: "Generated MineMotion starter content" },
  dependencies: [],
  estimatedSizeBytes: 24000,
  license: "MineMotion-generated",
  attribution: "Generated by MineMotion Studio; no Mojang/Microsoft assets included.",
  tags: ["builtin", "starter"],
  create(settings) {
    return updateProjectSettings(createInitialProject(settings), {
      projectName: "Flat Minecraft World",
      terrainPreset: "flat"
    });
  }
};

