import type { ProjectTemplate } from "../TemplateTypes";
import { createInitialProject, updateProjectSettings } from "../../project/ProjectStore";

export const NetherMoodTemplate: ProjectTemplate = {
  id: "nether-mood",
  name: "Nether Mood",
  description: "Nether-inspired sky, darker terrain palette, and low lighting.",
  category: "mood",
  schemaVersion: 1,
  templateVersion: 1,
  preview: { accent: "#6aa7ff", icon: "mood", aspectRatio: "16:9", summary: "Generated MineMotion starter content" },
  dependencies: [],
  estimatedSizeBytes: 24000,
  license: "MineMotion-generated",
  attribution: "Generated by MineMotion Studio; no Mojang/Microsoft assets included.",
  tags: ["builtin", "starter"],
  create(settings) {
    const project = updateProjectSettings(createInitialProject(settings), {
      projectName: "Nether Mood",
      defaultSkyPreset: "Nether",
      terrainPreset: "nether",
      blockPaletteStyle: "nether"
    });
    return {
      ...project,
      sky: {
        ...project.sky,
        preset: "Nether",
        customColor: "#3b1010"
      }
    };
  }
};

