import type { ProjectTemplate } from "../TemplateTypes";
import { createInitialProject, updateProjectSettings } from "../../project/ProjectStore";

export const SunsetSceneTemplate: ProjectTemplate = {
  id: "sunset-showcase",
  name: "Sunset Showcase",
  description: "Warm sky, terrain, character, and cinematic camera.",
  category: "mood",
  schemaVersion: 1,
  templateVersion: 1,
  preview: { accent: "#6aa7ff", icon: "mood", aspectRatio: "16:9", summary: "Generated MineMotion starter content" },
  dependencies: [],
  estimatedSizeBytes: 24000,
  license: "MineMotion-generated",
  attribution: "Generated by BlockMotion Studio; no Mojang/Microsoft assets included.",
  tags: ["builtin", "starter"],
  create(settings) {
    const project = updateProjectSettings(createInitialProject(settings), {
      projectName: "Sunset Showcase",
      defaultSkyPreset: "Sunset",
      terrainPreset: "demo"
    });
    return {
      ...project,
      sky: {
        ...project.sky,
        preset: "Sunset"
      },
      scene: {
        ...project.scene,
        cameras: project.scene.cameras.map((camera) => ({
          ...camera,
          transform: {
            ...camera.transform,
            position: [7, 4.5, 9],
            rotation: [-20, 38, 0]
          },
          fov: 40
        }))
      }
    };
  }
};

