import { QUICK_VFX_PRESET_IDS } from "./QuickVfxStudio";
import { STUDIO_FINISH_IDS } from "./PostFinishStudio";
import { RIG_GROUP_FORMATIONS } from "./MultiRigStudio";
import { VOXEL_MODEL_TEMPLATE_IDS, VOXEL_PRIMITIVE_KINDS } from "./VoxelModelingAdvanced";
import { MINECRAFT_STRUCTURE_TEMPLATE_IDS } from "./MinecraftBuilderAdvanced";

export interface MinecraftCreationFeatureSeed {
  id: string;
  title: string;
  sourceOwner: string;
  acceptanceId: string;
}

const item = (id: string, title: string, sourceOwner: string, acceptanceId = `creation-${id.replace(/\./g, "-")}`): MinecraftCreationFeatureSeed => ({ id: `creation.${id}`, title, sourceOwner: sourceOwner.startsWith("src/") ? sourceOwner : `src/minecraft/studio/${sourceOwner}`, acceptanceId });

export const MINECRAFT_CREATION_FEATURE_SEEDS: readonly MinecraftCreationFeatureSeed[] = [
  item("world.configure", "Configure Minecraft seed, version, loader and bounded area", "MinecraftWorldStudio.ts"),
  item("world.area-plan", "Prioritized bounded chunk and LOD plan", "WorldAreaPlanner.ts"),
  item("world.seed-hash", "Deterministic seed hashing", "WorldAreaPlanner.ts"),
  item("world.proxy-generate", "Deterministic bounded proxy terrain generation", "WorldProxyGenerator.ts"),
  item("world.proxy-build", "Build bounded seed proxy into the active scene", "MinecraftWorldStudio.ts"),
  item("world.blank-stage", "Create optimized blank Minecraft stage", "MinecraftWorldStudio.ts"),
  item("world.manifest", "Export Minecraft World Studio manifest", "MinecraftWorldStudio.ts"),
  item("world.loader-version", "Persist Vanilla, Fabric, Forge, NeoForge or Quilt target", "MinecraftWorldStudio.ts"),
  item("world.exact-source-guard", "Warn when an exact world requires an imported save", "WorldAreaPlanner.ts"),
  item("world.streaming-select", "Stream only bounded imported chunks around the active camera", "WorldStreamingStudio.ts"),
  item("world.streaming-lod", "Classify bounded chunks into near, medium and far LOD tiers", "WorldStreamingStudio.ts"),
  item("world.streaming-report", "Analyze active and unloaded world chunks", "WorldStreamingStudio.ts"),
  item("world.streaming-manifest", "Export bounded world streaming manifest", "WorldStreamingStudio.ts"),
  item("world.streaming-simplify", "Reduce medium and far chunks to surface/detail samples", "WorldStreamingStudio.ts"),
  item("world.streaming-reduction", "Estimate real render-block reduction from LOD streaming", "WorldStreamingStudio.ts"),
  item("mods.parse-manifest", "Parse safe mod asset manifest", "ModAssetCatalog.ts"),
  item("mods.upsert", "Add or update a mod catalog entry", "ModAssetCatalog.ts"),
  item("mods.toggle", "Enable or disable a mod catalog entry", "ModAssetCatalog.ts"),
  item("mods.remove", "Remove a mod catalog entry", "ModAssetCatalog.ts"),
  item("mods.compatibility", "Analyze mod loader compatibility", "ModAssetCatalog.ts"),
  item("mods.entity-catalog", "Combine Vanilla and compatible mod entities", "ModAssetCatalog.ts"),
  item("mods.assets-discover", "Discover imported assets matching a mod namespace", "ModAssetBridge.ts"),
  item("mods.assets-bind", "Bind resource packs, Blockbench and OBJ assets to a mod", "ModAssetBridge.ts"),
  item("mods.assets-resource-pack", "Activate a mod resource pack for world rendering", "ModAssetBridge.ts"),
  item("mods.assets-insert", "Insert a directly usable mod asset into the scene", "ModAssetBridge.ts"),
  item("mods.assets-block-palette", "Create a renderable palette prop from mod block IDs", "ModAssetBridge.ts"),
  item("mods.assets-manifest", "Export mod asset usage and compatibility manifest", "ModAssetBridge.ts"),
  ...(["set", "erase", "fill", "replace", "clone"] as const).map((kind) => item(`build.${kind}`, `Non-destructive world edit: ${kind}`, "WorldEditLayer.ts")),
  item("build.update", "Update a non-destructive world edit", "WorldEditLayer.ts"),
  item("build.remove", "Remove a non-destructive world edit", "WorldEditLayer.ts"),
  item("build.clear", "Clear all non-destructive world edits", "WorldEditLayer.ts"),
  item("build.apply", "Evaluate world edits over imported/proxy chunks", "WorldEditLayer.ts"),
  item("build.bake", "Bake world-edit layers into the project copy", "WorldEditLayer.ts"),
  item("build.manifest", "Export world-edit layer manifest", "WorldEditLayer.ts"),
  ...MINECRAFT_STRUCTURE_TEMPLATE_IDS.map((template) => item(`build.structure.${template}`, `Procedural Minecraft structure: ${template}`, "MinecraftBuilderAdvanced.ts")),
  item("build.brush-line", "Draw a bounded three-dimensional block line", "MinecraftBuilderAdvanced.ts"),
  item("build.brush-sphere", "Create solid or hollow Minecraft sphere brush", "MinecraftBuilderAdvanced.ts"),
  item("build.brush-cylinder", "Create solid or hollow Minecraft cylinder brush", "MinecraftBuilderAdvanced.ts"),
  item("build.layer-mirror", "Mirror the non-destructive builder layer", "MinecraftBuilderAdvanced.ts"),
  item("build.layer-duplicate", "Duplicate the builder layer with an offset", "MinecraftBuilderAdvanced.ts"),
  item("build.blueprint-export", "Export reusable relative Minecraft blueprint", "MinecraftBuilderAdvanced.ts"),
  item("build.blueprint-import", "Import safe Minecraft blueprint at a destination", "MinecraftBuilderAdvanced.ts"),
  item("build.selection-analyze", "Measure builder bounds and estimated block cost", "MinecraftBuilderAdvanced.ts"),
  item("model.create", "Create voxel model asset", "VoxelModeling.ts"),
  item("model.add-cube", "Add editable voxel cube", "VoxelModeling.ts"),
  item("model.update-cube", "Edit voxel cube transform and material", "VoxelModeling.ts"),
  item("model.remove-cube", "Remove voxel cube", "VoxelModeling.ts"),
  item("model.mirror", "Mirror voxel model on any axis", "VoxelModeling.ts"),
  item("model.array", "Array voxel geometry", "VoxelModeling.ts"),
  item("model.optimize", "Deduplicate and clean voxel geometry", "VoxelModeling.ts"),
  item("model.from-world", "Extract voxel model from world selection", "VoxelModeling.ts"),
  item("model.obj", "Compile voxel model to OBJ", "VoxelModeling.ts"),
  item("model.scene-sync", "Synchronize voxel model with renderer asset", "VoxelModeling.ts"),
  item("model.delete", "Delete voxel model and linked scene asset", "VoxelModeling.ts"),
  item("model.manifest", "Export voxel model manifest", "VoxelModeling.ts"),
  ...VOXEL_PRIMITIVE_KINDS.map((kind) => item(`model.primitive.${kind}`, `Voxel primitive: ${kind}`, "VoxelModelingAdvanced.ts")),
  ...VOXEL_MODEL_TEMPLATE_IDS.map((template) => item(`model.template.${template}`, `Minecraft model template: ${template}`, "VoxelModelingAdvanced.ts")),
  item("model.duplicate", "Duplicate voxel model independently", "VoxelModelingAdvanced.ts"),
  item("model.transform", "Transform complete voxel model", "VoxelModelingAdvanced.ts"),
  item("model.recolor", "Recolor and rematerial complete voxel model", "VoxelModelingAdvanced.ts"),
  item("model.center-origin", "Center voxel model origin", "VoxelModelingAdvanced.ts"),
  item("model.merge-adjacent", "Merge adjacent compatible voxel cubes", "VoxelModelingAdvanced.ts"),
  item("rig.spawn", "Spawn ready-made Vanilla or mod catalog rig", "MultiRigAnimator.ts"),
  item("rig.group-create", "Create multi-rig animation group", "MultiRigAnimator.ts"),
  item("rig.group-update", "Configure group stagger, mirror and speed", "MultiRigAnimator.ts"),
  item("rig.group-delete", "Delete multi-rig group without deleting actors", "MultiRigAnimator.ts"),
  item("rig.preset", "Apply one animation preset to many rigs", "MultiRigAnimator.ts"),
  item("rig.sync-pose", "Synchronize compatible bones across a rig group", "MultiRigAnimator.ts"),
  item("rig.mirror-pose", "Mirror a complete rig group pose", "MultiRigAnimator.ts"),
  item("rig.offset", "Offset all group animation timing", "MultiRigAnimator.ts"),
  item("rig.manifest", "Export multi-rig group manifest", "MultiRigAnimator.ts"),
  item("rig.simple-auto", "Auto-rig a voxel model with an animatable Minecraft skeleton", "SimpleRiggingStudio.ts"),
  item("rig.simple-rebind", "Reassign a voxel cube to another rig bone", "SimpleRiggingStudio.ts"),
  item("rig.simple-update", "Edit rigged cube transform and material", "SimpleRiggingStudio.ts"),
  item("rig.simple-display", "Toggle custom and default rig geometry", "SimpleRiggingStudio.ts"),
  item("rig.simple-refresh", "Refresh rig geometry from its source voxel model", "SimpleRiggingStudio.ts"),
  item("rig.simple-validate", "Validate bone assignments and rig density", "SimpleRiggingStudio.ts"),
  item("rig.simple-export", "Export editable simple rig manifest", "SimpleRiggingStudio.ts"),
  item("rig.simple-detach", "Detach custom geometry without deleting animation", "SimpleRiggingStudio.ts"),
  item("rig.crowd", "Spawn and group a bounded crowd", "MultiRigStudio.ts"),
  ...RIG_GROUP_FORMATIONS.map((formation) => item(`rig.formation.${formation}`, `Multi-rig formation: ${formation}`, "MultiRigStudio.ts")),
  item("rig.translate", "Animate a whole rig group through space", "MultiRigStudio.ts"),
  item("rig.retime", "Retime all tracks in a rig group", "MultiRigStudio.ts"),
  item("rig.variation", "Add deterministic crowd timing variation", "MultiRigStudio.ts"),
  item("rig.face-target", "Orient a rig group toward a target", "MultiRigStudio.ts"),
  item("rig.mute", "Mute NLA animation for a rig group", "MultiRigStudio.ts"),
  item("rig.remove-animation", "Remove animation from a rig group", "MultiRigStudio.ts"),
  item("collision.enable", "Enable or disable Collision Studio", "CollisionStudio.ts"),
  item("collision.world-toggle", "Toggle world collision", "CollisionStudio.ts"),
  item("collision.entity-toggle", "Toggle entity collision", "CollisionStudio.ts"),
  item("collision.visualization", "Toggle collision helper visualization", "CollisionStudio.ts"),
  item("collision.default-profiles", "Create collision profiles from rig/object type", "CollisionStudio.ts"),
  item("collision.custom-profile", "Edit per-entity collision profile", "CollisionStudio.ts"),
  item("collision.remove-profile", "Remove per-entity collision override", "CollisionStudio.ts"),
  item("collision.aabb", "Compute scaled entity collision bounds", "CollisionStudio.ts"),
  item("collision.analyze", "Analyze entity and world contacts", "CollisionStudio.ts"),
  item("collision.snap", "Snap one entity to edited world surface", "CollisionStudio.ts"),
  item("collision.snap-all", "Snap all collidable entities to world", "CollisionStudio.ts"),
  item("collision.resolve", "Resolve entity overlap iteratively", "CollisionStudio.ts"),
  item("collision.helpers", "Synchronize renderer collision helpers", "CollisionStudio.ts"),
  item("collision.manifest", "Export collision analysis manifest", "CollisionStudio.ts"),
  item("collision.timeline-analyze", "Analyze collisions across an animation frame range", "CollisionAnimationBaker.ts"),
  item("collision.timeline-bake", "Bake collision-avoidance position keys into animation", "CollisionAnimationBaker.ts"),
  item("collision.timeline-export", "Export animation collision preflight report", "CollisionAnimationBaker.ts"),
  ...QUICK_VFX_PRESET_IDS.map((preset) => item(`vfx.${preset}`, `One-click Minecraft VFX: ${preset}`, "QuickVfxStudio.ts")),
  item("vfx.favorite-add", "Save Quick VFX favorite", "QuickVfxStudio.ts"),
  item("vfx.favorite-insert", "Insert saved Quick VFX favorite", "QuickVfxStudio.ts"),
  item("vfx.favorite-remove", "Remove Quick VFX favorite", "QuickVfxStudio.ts"),
  item("vfx.remove-at-frame", "Remove VFX around playhead", "QuickVfxStudio.ts"),
  item("vfx.catalog-export", "Export Quick VFX recipe catalog", "QuickVfxStudio.ts"),
  ...STUDIO_FINISH_IDS.map((finish) => item(`post.finish.${finish}`, `Studio finish: ${finish}`, "PostFinishStudio.ts")),
  item("post.stack-add", "Add non-destructive post layer", "PostFinishStudio.ts"),
  item("post.stack-update", "Edit post layer weight and state", "PostFinishStudio.ts"),
  item("post.stack-move", "Reorder post layers", "PostFinishStudio.ts"),
  item("post.stack-remove", "Remove post layer", "PostFinishStudio.ts"),
  item("post.stack-clear", "Clear post stack", "PostFinishStudio.ts"),
  item("post.stack-evaluate", "Blend post stack deterministically", "PostFinishStudio.ts"),
  item("post.stack-flatten", "Flatten post stack into project settings", "PostFinishStudio.ts"),
  item("post.finish-stack", "Create post stack from finish recipe", "PostFinishStudio.ts"),
  item("post.manifest", "Export post-production manifest", "PostFinishStudio.ts"),
  item("performance.analyze", "Analyze Minecraft Studio resource budgets", "MinecraftStudioOptimization.ts"),
  item("performance.target", "Apply low-end, balanced or cinematic target", "MinecraftStudioOptimization.ts"),
  item("performance.models", "Optimize all voxel models", "MinecraftStudioOptimization.ts"),
  item("performance.effects", "Disable VFX outside active world area", "MinecraftStudioOptimization.ts"),
  item("performance.auto", "One-click Minecraft Studio optimization", "MinecraftStudioOptimization.ts"),
  item("performance.report", "Export optimization report", "MinecraftStudioOptimization.ts"),
  item("package.create", "Create exportable Minecraft Creation Suite package", "MinecraftStudioPackage.ts"),
  item("package.serialize", "Serialize complete creation package", "MinecraftStudioPackage.ts"),
  item("package.streaming", "Include bounded world streaming plan in delivery package", "MinecraftStudioPackage.ts"),
  item("package.blueprint", "Include reusable builder blueprint in delivery package", "MinecraftStudioPackage.ts"),
  item("package.simple-rigs", "Include editable simple rigs in delivery package", "MinecraftStudioPackage.ts"),
  item("package.mod-assets", "Include per-mod imported asset reports in delivery package", "MinecraftStudioPackage.ts"),
  item("persistence.roundtrip", "Persist and reload all Creation Suite data", "MinecraftStudioDefaults.ts"),
  item("persistence.custom-rig", "Persist and sanitize custom voxel rig geometry", "src/rigs/RigSerializer.ts")
];
