export const EN_TRANSLATIONS = Object.freeze({
  "common.close": "Close",
  "common.enabled": "Enabled",
  "common.disabled": "Disabled",
  "common.none": "None",
  "common.low": "Low",
  "common.medium": "Medium",
  "common.high": "High",
  "topbar.mainActions": "Main actions",
  "topbar.newProject": "New Project",
  "topbar.templates": "Templates",
  "topbar.openWorld": "Open World",
  "topbar.saveProject": "Save Project",
  "topbar.loadProject": "Load Project",
  "topbar.addCharacter": "Add Character",
  "topbar.addCamera": "Add Camera",
  "topbar.importObj": "Import OBJ",
  "topbar.pause": "Pause",
  "topbar.play": "Play",
  "topbar.settings": "Settings",
  "topbar.plugins": "Plugins",
  "topbar.commands": "Commands",
  "topbar.export": "Export",
  "topbar.rigStudio": "Rig Studio",
  "topbar.lighting": "Lighting",
  "topbar.vfxStudio": "VFX Studio",
  "topbar.help": "Help",
  "topbar.viewport": "Viewport",
  "topbar.renderPreview": "Render Preview",
  "settings.title": "Settings",
  "settings.app": "App Settings",
  "settings.language": "Language",
  "settings.language.system": "System language",
  "settings.language.english": "English",
  "settings.language.french": "French",
  "settings.autosaveEnabled": "Autosave enabled",
  "settings.autosaveInterval": "Autosave interval (s)",
  "settings.defaultFps": "Default FPS",
  "settings.defaultDuration": "Default duration",
  "settings.defaultNamePattern": "Default name pattern",
  "settings.viewport": "Viewport",
  "settings.backgroundColor": "Background color",
  "settings.showGrid": "Show grid",
  "settings.gridSize": "Grid size",
  "settings.orbitSpeed": "Orbit speed",
  "settings.renderQuality": "Render quality",
  "settings.editor": "Editor",
  "settings.theme": "Theme",
  "settings.theme.dark": "Dark",
  "settings.theme.lightPlaceholder": "Light placeholder",
  "settings.uiScale": "UI scale",
  "settings.snapToGrid": "Snap to grid",
  "settings.transformStep": "Transform step",
  "settings.rotationStep": "Rotation step",
  "settings.minecraft": "Minecraft",
  "settings.defaultSky": "Default sky",
  "settings.blockPaletteStyle": "Block palette style",
  "settings.palette.classic": "Classic",
  "settings.palette.muted": "Muted",
  "settings.palette.nether": "Nether",
  "settings.defaultTerrainSize": "Default terrain size",
  "settings.resourcePackPath": "Resource pack path",
  "settings.project": "Project Settings",
  "settings.projectName": "Project name",
  "settings.fps": "FPS",
  "settings.durationFrames": "Duration frames",
  "settings.terrainPreset": "Terrain preset",
  "settings.terrain.demo": "Demo",
  "settings.terrain.flat": "Flat",
  "settings.terrain.nether": "Nether",
  "settings.resolutionPreset": "Resolution preset",
  "settings.resolution.custom": "Custom",
  "settings.author": "Author",
  "settings.notes": "Notes",
  "settings.plugins": "Plugins",
  "settings.plugins.enabled": "Enable built-in plugin registry",
  "settings.plugins.experimental": "Allow experimental plugin manifests",
  "settings.plugins.folder": "Plugin folder path",
  "settings.plugins.executionDisabled": "External plugin JavaScript execution is disabled in this build.",
  "help.ariaLabel": "MineMotion help",
  "help.quickStart": "Quick Start",
  "help.loadSampleScene": "Load Sample Scene",
  "help.orbit": "Drag in the viewport to orbit, right-drag to pan, wheel to zoom.",
  "help.select": "Select objects in the viewport or outliner.",
  "help.transforms": "Edit transforms in the inspector.",
  "help.keyframes": "Add a keyframe, move to another frame, edit, then add another.",
  "help.effects": "Add cinematic effects from the Effects panel at the current frame.",
  "help.postProcessing": "Use post-processing presets for cinematic looks.",
  "help.renderPreview": "Toggle Render Preview to view bars, post effects, and active camera framing.",
  "help.sfx": "Import SFX or add placeholder SFX to the timeline.",
  "help.play": "Use Play to preview linear animation.",
  "help.worldImport": "World import scans real Java world folders and can load selected chunks.",
  "help.save": "Save projects as `.minemotion` packages; legacy `.mmsproj` export is in Export.",
  "help.shortcuts": "Keyboard Shortcuts",
  "help.shortcut.commands": "Ctrl+P — open the command palette",
  "help.shortcut.save": "Ctrl+S — save the current project",
  "help.shortcut.undo": "Ctrl+Z / Ctrl+Y — undo / redo",
  "help.shortcut.duplicate": "Ctrl+D — duplicate the selected object or effect",
  "help.shortcut.delete": "Delete — delete the selected object or effect",
  "help.shortcut.play": "Space — play or pause the timeline",
  "outliner.title": "Outliner",
  "outliner.scene": "Scene",
  "outliner.characters": "Characters",
  "outliner.cameras": "Cameras",
  "outliner.objAssets": "OBJ Assets",
  "outliner.lights": "Lights",
  "outliner.demoWorld": "Demo World",
  "outliner.world.scanned": "scanned world",
  "outliner.world.generated": "generated terrain",
  "outliner.chunks.one": "{count} chunk",
  "outliner.chunks.other": "{count} chunks",
  "outliner.noObj": "No OBJ objects imported.",
  "outliner.bone": "bone",
  "outliner.entity.character": "character",
  "outliner.entity.camera": "camera",
  "outliner.entity.object": "object",
  "outliner.entity.light": "light",
  "commands.ariaLabel": "Command palette",
  "commands.searchPlaceholder": "Type a command...",
  "commands.group.project": "Project",
  "commands.group.scene": "Scene",
  "commands.group.timeline": "Timeline",
  "commands.group.view": "View",
  "commands.group.settings": "Settings",
  "commands.group.plugins": "Plugins",
  "commands.group.effects": "Effects",
  "commands.group.render": "Render",
  "commands.group.post": "Post",
  "commands.newProject": "New Project",
  "commands.saveProject": "Save Project",
  "commands.loadProject": "Load Project",
  "commands.savePackage": "Save .minemotion Package",
  "commands.exportLegacy": "Export Legacy .mmsproj",
  "commands.addCharacter": "Add Character",
  "commands.addCamera": "Add Camera",
  "commands.importObj": "Import OBJ",
  "commands.duplicateSelected": "Duplicate Selected Object",
  "commands.deleteSelected": "Delete Selected Object",
  "commands.openSettings": "Open Settings",
  "commands.openPlugins": "Open Plugin Manager",
  "commands.applySky": "Apply Sky: {sky}",
  "commands.sky.day": "Day",
  "commands.sky.sunset": "Sunset",
  "commands.sky.night": "Night",
  "commands.toggleTimeline": "Play/Pause Timeline",
  "commands.resetCamera": "Reset Viewport Camera",
  "commands.addKeyframe": "Add Keyframe",
  "commands.effect.lightningStrike": "Add Lightning Strike",
  "commands.effect.impactFrame": "Add Impact Frame",
  "commands.effect.cameraShake": "Add Camera Shake",
  "commands.effect.flash": "Add Flash",
  "commands.effect.speedLines": "Add Speed Lines",
  "commands.effect.shockwave": "Add Shockwave",
  "commands.effect.glowBurst": "Add Glow Burst",
  "commands.togglePreview": "Toggle Render Preview",
  "commands.toggleBars": "Toggle Cinematic Bars",
  "commands.openExport": "Open Export Panel",
  "commands.exportFrame": "Export Current Frame PNG",
  "commands.exportSequence": "Export PNG Sequence ZIP",
  "commands.post.cinematicWarm": "Post: Cinematic Warm",
  "commands.post.darkHorror": "Post: Dark Horror",
  "commands.post.animeImpact": "Post: Anime Impact",
  "commands.post.retroPixel": "Post: Retro Pixel",
  "commands.undo": "Undo",
  "commands.redo": "Redo",
  "templates.ariaLabel": "New project from template",
  "templates.title": "New Project From Template",
  "templates.category.starter": "Starter",
  "templates.category.animation": "Animation",
  "templates.category.cinematic": "Cinematic",
  "templates.category.mood": "Mood",
  "templates.emptyScene.name": "Empty Scene",
  "templates.emptyScene.description": "Grid, default camera, default sky, no terrain or characters.",
  "templates.flatWorld.name": "Flat Minecraft World",
  "templates.flatWorld.description": "Flat grass and dirt test world with one camera and light.",
  "templates.characterAnimation.name": "Character Animation Test",
  "templates.characterAnimation.description": "One character with starter movement keyframes over 120 frames.",
  "templates.cinematicCamera.name": "Cinematic Camera Test",
  "templates.cinematicCamera.description": "Terrain and a keyframed camera push-in.",
  "templates.sunset.name": "Sunset Showcase",
  "templates.sunset.description": "Warm sky, terrain, character, and cinematic camera.",
  "templates.nether.name": "Nether Mood",
  "templates.nether.description": "Nether-inspired sky, darker terrain palette, and low lighting.",
  "plugins.ariaLabel": "Plugin manager",
  "plugins.title": "Plugin Manager",
  "plugins.securityNotice": "External plugin JavaScript execution is disabled in this build. Built-in plugins are bundled TypeScript modules; external manifests should not be executed without a future sandbox.",
  "plugins.builtin": "built-in",
  "plugins.externalManifest": "external manifest",
  "effects.title": "Effects",
  "effects.library": "Library",
  "effects.search": "Search VFX",
  "effects.searchAria": "Search VFX presets",
  "effects.sourceAria": "VFX preset source",
  "effects.source.all": "All {count}",
  "effects.source.builtin": "Built-in {count}",
  "effects.source.custom": "Custom {count}",
  "effects.categoryAria": "Filter VFX category",
  "effects.allCategories": "All categories",
  "effects.tagAria": "Add VFX tag filter",
  "effects.addTag": "Add tag",
  "effects.favorites": "Favorites",
  "effects.activeTagsAria": "Active VFX tag filters",
  "effects.recent": "Recent",
  "effects.results.one": "{count} result",
  "effects.results.other": "{count} results",
  "effects.previewPending": "Preview pending",
  "effects.builtinMaturity": "Built-in / {maturity}",
  "effects.customSpace": "Custom / {space}",
  "effects.favorite.add": "Add {name} to favorites",
  "effects.favorite.remove": "Remove {name} from favorites",
  "effects.emptyCustom": "No custom VFX packages are installed.",
  "effects.emptyFiltered": "No VFX presets match these filters.",
  "effects.scene": "Scene Effects",
  "effects.projectCount.one": "{count} effect in this project.",
  "effects.projectCount.other": "{count} effects in this project.",
  "effects.sceneAria": "Scene effects",
  "effects.sourceMissing": "{state} / source package missing (embedded recipe kept)",
  "effects.sourceDisabled": "{state} / source package disabled (embedded recipe kept)",
  "effects.sourceVersionChanged": "{state} / source package version changed (embedded recipe kept)",
  "effects.addFromLibrary": "Add an effect from the library.",
  "effects.post": "Post",
  "effects.renderPreview": "Render Preview",
  "effects.leavePreview": "Leave Preview",
  "effects.enterPreview": "Enter Preview",
  "effects.hideBars": "Hide Bars",
  "effects.showBars": "Show Bars",
  "effects.sfx": "SFX",
  "effects.importSfx": "Import SFX",
  "effects.audioCount.one": "{count} audio clip on timeline.",
  "effects.audioCount.other": "{count} audio clips on timeline.",
  "vfx.title": "VFX Workspace",
  "vfx.closeAria": "Close VFX Workspace",
  "vfx.safeSource": "Safe Draft Source",
  "vfx.stableBuiltin": "Stable native built-in",
  "vfx.derive": "Derive Draft Copy",
  "vfx.newBlank": "New Blank Draft",
  "vfx.packageAuthor": "Package author",
  "vfx.license": "SPDX license",
  "vfx.exportPackage": "Export .minemotion-vfx",
  "vfx.inspectPackage": "Inspect Package",
  "vfx.safety": "Declarative data only. JavaScript, executable plugins, and unrestricted shaders are not accepted.",
  "vfx.draftSettings": "Draft Settings",
  "vfx.durationFrames": "Duration (frames)",
  "vfx.targetEntity": "Target entity",
  "vfx.targetEntityPlaceholder": "Optional entity ID",
  "vfx.targetBone": "Target bone",
  "vfx.targetBonePlaceholder": "Optional bone ID",
  "vfx.previewQuality": "Preview quality",
  "vfx.exportQuality": "Export quality",
  "vfx.quality.draft": "Draft",
  "vfx.quality.medium": "Medium",
  "vfx.quality.high": "High",
  "vfx.quality.final": "Final",
  "vfx.previewAlt": "Preview of {name}",
  "vfx.work": "{primitives} primitives / {particles} particles / {segments} segments",
  "vfx.itemEditor": "Item Editor",
  "vfx.label": "Label",
  "vfx.color": "Color",
  "vfx.tint": "Tint",
  "vfx.primaryValue": "Primary value",
  "vfx.modifierScope": "{kind} applies to all enabled items above it.",
  "vfx.selectItem": "Select a stack item to edit it.",
  "vfx.stack": "Stack ({count}/16)",
  "vfx.add": "Add",
  "vfx.stackAria": "VFX authoring stack",
  "vfx.moveUp": "Move {name} up",
  "vfx.moveDown": "Move {name} down",
  "vfx.duplicate": "Duplicate {name}",
  "vfx.enable": "Enable {name}",
  "vfx.disable": "Disable {name}",
  "vfx.delete": "Delete {name}",
  "vfx.emptyStack": "Add a primitive, emitter, or restricted modifier.",
  "vfx.report": "Pre-install Package Report",
  "vfx.packagePreviewAlt": "Package preview for {name}",
  "vfx.package": "Package",
  "vfx.authorLicense": "Author / license",
  "vfx.installReadiness": "Install readiness",
  "vfx.ready": "Ready",
  "vfx.missingDependencies": "Missing required dependencies",
  "vfx.runtimeWork": "Runtime work",
  "vfx.assets": "Assets",
  "vfx.packageLicense": "package license",
  "vfx.dependencies": "Dependencies",
  "vfx.permissions": "Permissions",
  "vfx.optional": "optional",
  "vfx.dependency.satisfied": "satisfied",
  "vfx.dependency.missing": "missing",
  "vfx.dependency.version-mismatch": "version mismatch",
  "vfx.permission.asset-textures": "Use package-provided textures and sprites.",
  "vfx.permission.asset-audio": "Use package-provided audio during preview and export.",
  "vfx.permission.asset-models": "Use package-provided supported model data.",
  "vfx.permission.restricted-shader-templates": "Use validated built-in shader template parameters only.",
  "vfx.inspectionOnly": "Inspection only. This package has not been installed, enabled, or written to local storage.",
  "vfx.installedInspection": "Read-only inspection of an already installed local package.",
  "vfx.updateInstalled": "Update Installed Package",
  "vfx.installLocally": "Install Package Locally",
  "vfx.installedPackages": "Installed Custom Packages ({count}/32)",
  "vfx.inspect": "Inspect",
  "vfx.enableAction": "Enable",
  "vfx.disableAction": "Disable",
  "vfx.uninstall": "Uninstall",
  "vfx.noInstalled": "No custom VFX packages are installed locally.",
  "vfx.message.blank": "Blank declarative draft ready.",
  "vfx.message.noChange": "No VFX draft change.",
  "vfx.message.authoringInvalid": "The VFX draft change is invalid. Check the field limits and try again.",
  "vfx.message.chooseBuiltin": "Choose a stable native built-in first.",
  "vfx.message.derived": "Created a custom draft copy without changing {name}.",
  "vfx.message.deriveFailed": "Could not derive the selected preset.",
  "vfx.message.compileFailed": "The VFX draft cannot be compiled within the supported schema and budgets.",
  "vfx.message.exported": "Exported deterministic package {filename}.",
  "vfx.message.exportFailed": "Could not export VFX package.",
  "vfx.message.inspected": "Inspected {name}. Nothing was installed or changed.",
  "vfx.message.inspectFailed": "Could not inspect VFX package.",
  "vfx.message.storageFailed": "Local VFX package storage is full or unavailable; no registry change was kept.",
  "vfx.message.installed": "{name} installed locally.",
  "vfx.message.updated": "{name} updated locally.",
  "vfx.message.installFailed": "Could not install VFX package.",
  "vfx.message.state": "{id} {state}.",
  "vfx.message.stateFailed": "Could not change VFX package state.",
  "vfx.message.confirmUninstall": "Uninstall local VFX package {id}?",
  "vfx.message.uninstalled": "{id} uninstalled locally.",
  "vfx.message.uninstallFailed": "Could not uninstall VFX package.",
  "vfx.message.inspectingInstalled": "Inspecting installed package {id}.",
  "world.title": "World Import",
  "world.ariaLabel": "World import",
  "world.folder": "World Folder",
  "world.chooseFolder": "Choose Folder",
  "world.focus": "Focus World",
  "world.unload": "Unload",
  "world.info.folder": "Folder",
  "world.info.level": "Level",
  "world.info.dataVersion": "Data version",
  "world.info.spawn": "Spawn",
  "world.unknown": "unknown",
  "world.scanPrompt": "Select a Minecraft world folder to scan `level.dat` and `.mca` region files.",
  "world.selection": "Import Selection",
  "world.dimension": "Dimension",
  "world.dimension.overworld": "Overworld",
  "world.dimension.nether": "Nether",
  "world.dimension.end": "End",
  "world.centerX": "Center chunk X",
  "world.centerZ": "Center chunk Z",
  "world.radius": "Radius",
  "world.maxChunks": "Max chunks",
  "world.maxRegions": "Max regions",
  "world.maxSections": "Max sections",
  "world.showBorders": "Show chunk borders",
  "world.showOrigin": "Show world origin",
  "world.embedCache": "Embed imported chunk cache in project",
  "world.dimensions": "Dimensions",
  "world.regions.one": "{count} region",
  "world.regions.other": "{count} regions",
  "world.estimatedChunks.one": "{count} estimated chunk",
  "world.estimatedChunks.other": "{count} estimated chunks",
  "world.noScan": "No folder scanned yet.",
  "world.selectedRegions.one": "Selected dimension has {count} region file.",
  "world.selectedRegions.other": "Selected dimension has {count} region files.",
  "world.runImport": "Run Import",
  "world.importChunks": "Import Chunks",
  "world.cancel": "Cancel",
  "world.chunks": "Chunks",
  "world.blocks": "Blocks",
  "world.unknownBlocks": "Unknown",
  "world.warnings": "Warnings",
  "world.status.idle": "Idle",
  "world.status.scanning": "Scanning",
  "world.status.reading-level": "Reading world metadata",
  "world.status.reading-regions": "Reading regions",
  "world.status.reading-chunks": "Reading chunks",
  "world.status.meshing": "Building geometry",
  "world.status.complete": "Complete",
  "world.status.cancelled": "Cancelled",
  "world.status.error": "Error",
  "world.progress.idle": "No world import is running.",
  "world.progress.scanning": "Scanning the selected world folder.",
  "world.progress.reading-level": "Reading validated level metadata.",
  "world.progress.reading-regions": "Reading selected region files.",
  "world.progress.reading-chunks": "Importing bounded Minecraft chunks.",
  "world.progress.meshing": "Building deterministic chunk geometry.",
  "world.progress.complete": "World import completed.",
  "world.progress.cancelled": "World import was cancelled.",
  "world.progress.error": "World import stopped with an error.",
  "rig.title": "Rig Studio",
  "rig.closeAria": "Close rig studio",
  "rig.selectedCharacter": "Selected Character",
  "rig.selectPrompt": "Add or select a character first.",
  "rig.poseLibrary": "Pose Library",
  "rig.animationPresets": "Animation Presets",
  "rig.blockbench": "Blockbench",
  "rig.importBlockbench": "Import Blockbench Model",
  "rig.noBlockbench": "No .bbmodel imported yet.",
  "rig.modelCounts": "{cubes} cubes / {groups} groups / {textures} textures",
  "rig.skin": "Skin",
  "rig.fallbackColors": "fallback colors",
  "rig.resolution": "Resolution",
  "rig.model": "Model",
  "rig.status": "Status",
  "rig.valid": "valid",
  "rig.invalid": "invalid",
  "rig.importSkin": "Import Skin",
  "rig.resetSkin": "Reset Skin",
  "rig.savePose": "Save Current Pose",
  "rig.mirrorPose": "Mirror Pose",
  "rig.resetPose": "Reset Pose",
  "export.title": "Production Export",
  "export.ariaLabel": "Production export",
  "export.output": "Output",
  "export.outputName": "Output name",
  "export.format": "Format",
  "export.group.browserDesktop": "Browser and desktop",
  "export.group.ffmpeg": "Desktop + user-installed FFmpeg",
  "export.format.pngFrame": "PNG current frame",
  "export.format.pngSequence": "PNG sequence ZIP",
  "export.format.webm": "WebM video (video only)",
  "export.format.wav": "WAV audio mixdown",
  "export.format.package": ".minemotion package",
  "export.format.audioMetadata": "Audio metadata JSON",
  "export.format.mp4H264": "MP4 H.264",
  "export.format.mp4H265": "MP4 H.265",
  "export.format.prores": "ProRes MOV",
  "export.format.mp3": "MP3 audio",
  "export.startFrame": "Start frame",
  "export.endFrame": "End frame",
  "export.fps": "FPS",
  "export.quality": "Quality",
  "export.quality.draft": "Draft",
  "export.width": "Width",
  "export.height": "Height",
  "export.camera": "Camera",
  "export.activeCamera": "Active camera",
  "export.viewportCamera": "Viewport camera",
  "export.options": "Render Options",
  "export.includePost": "Include post-processing",
  "export.includeVfx": "Include cinematic VFX overlays",
  "export.includeBars": "Include cinematic bars",
  "export.transparent": "Transparent PNG background",
  "export.includeAudio": "Include audio where the selected format supports it",
  "export.ffmpeg": "FFmpeg Desktop",
  "export.ffmpegPath": "FFmpeg executable or path",
  "export.outputDirectory": "Native output directory",
  "export.encodingTarget": "Encoding target",
  "export.encoding.small": "Smaller file",
  "export.encoding.balanced": "Balanced",
  "export.encoding.high": "High quality",
  "export.overwrite": "Overwrite existing output",
  "export.preset.draft720": "Draft Preview 720p",
  "export.preset.youtube1080": "YouTube 1080p",
  "export.preset.youtube1440": "YouTube 1440p",
  "export.preset.vertical": "Vertical Shorts 1080x1920",
  "export.preset.cinematic": "Cinematic 2.35:1 1080p",
  "export.preset.square": "Square 1080",
  "export.preset.pngHigh": "High Quality PNG Sequence",
  "export.preset.pngTransparent": "Transparent PNG Sequence",
  "export.preset.webmSmall": "Low File Size WebM",
  "export.detectFfmpeg": "Detect FFmpeg",
  "export.validation": "Validation",
  "export.webmUnavailable": "WebM is unavailable in this runtime.",
  "export.audioUnavailable": "Audio mixdown is unavailable in this runtime.",
  "export.ffmpegAvailable": "Native FFmpeg is available.",
  "export.ffmpegUnavailable": "Native FFmpeg is unavailable or has not been detected.",
  "export.issue.cameraMissing": "No active or export camera is available.",
  "export.issue.frameOrder": "The start frame must be before or equal to the end frame.",
  "export.issue.frameEmpty": "The frame range must contain at least one frame.",
  "export.issue.endAfterProject": "The end frame is beyond the project duration; the last scene state will be held.",
  "export.issue.directoryMissing": "Choose an FFmpeg output directory before starting a native export.",
  "export.issue.nameMissing": "An output name is required.",
  "export.issue.webmUnsupported": "WebM export requires image bitmap, MediaRecorder, and canvas capture support.",
  "export.issue.webmVideoOnly": "Browser WebM contains video only; export WAV separately or use native MP4 for muxed audio.",
  "export.issue.wavUnsupported": "WAV mixdown requires browser OfflineAudioContext support.",
  "export.issue.muxUnsupported": "Native video audio muxing requires WAV mixdown support.",
  "export.issue.mp3MixdownUnsupported": "MP3 export requires WAV mixdown support before FFmpeg encoding.",
  "export.issue.mp3NativeOnly": "MP3 export requires FFmpeg; browser mode does not simulate it.",
  "export.issue.resolutionHigh": "Resolution is above 4K and may be slow in browser export.",
  "export.issue.sizeHigh": "Estimated output size is above 2 GB.",
  "export.issue.postDisabled": "Post-processing was requested but is disabled in project settings.",
  "export.issue.vfxEmpty": "VFX export is enabled but the project has no effect instances.",
  "export.issue.ffmpegRequired": "{format} requires native FFmpeg support.",
  "export.issue.assetsMissing": "{count} tracked assets are missing or invalid.",
  "export.issue.unmapped": "An export diagnostic could not be presented safely.",
  "export.runPackage": "Run or Package",
  "export.addQueue": "Add to Queue",
  "export.pngFrame": "PNG Frame",
  "export.pngZip": "PNG ZIP",
  "export.cancel": "Cancel",
  "export.savePackage": "Save .minemotion",
  "export.exportLegacy": "Export .mmsproj",
  "export.trackedAssets.one": "{count} tracked asset",
  "export.trackedAssets.other": "{count} tracked assets",
  "export.missingAssets.one": "{count} missing",
  "export.missingAssets.other": "{count} missing",
  "export.packageWarnings.one": "{count} package warning",
  "export.packageWarnings.other": "{count} package warnings",
  "export.renderQueue": "Render Queue",
  "export.check.camera": "Export camera",
  "export.check.frameRange": "Frame range",
  "export.check.format": "Format support",
  "export.check.assets": "Asset availability",
  "export.check.audio": "Audio compatibility",
  "export.check.frameCount": "Frame count",
  "export.check.size": "Estimated size",
  "export.check.post": "Post-processing state",
  "export.check.effects": "VFX state",
  "export.frames.one": "{count} frame",
  "export.frames.other": "{count} frames",
  "export.seconds": "{count} seconds",
  "export.approx": "Approx. {size}",
  "export.noRunning": "No export running.",
  "export.status.idle": "Idle",
  "export.status.preparing": "Preparing",
  "export.status.rendering": "Rendering",
  "export.status.encoding": "Encoding",
  "export.status.complete": "Complete",
  "export.status.cancelled": "Cancelled",
  "export.status.error": "Error",
  "export.progress.idle": "No export is running.",
  "export.progress.preparing": "Preparing the validated export.",
  "export.progress.rendering": "Rendering the selected frame range.",
  "export.progress.encoding": "Encoding the rendered output.",
  "export.progress.complete": "Export completed.",
  "export.progress.cancelled": "Export was cancelled.",
  "export.progress.error": "Export stopped with an error.",
  "export.runtimeFailed": "The export runtime failed. Check the selected format and runtime capabilities.",
  "queue.jobs.one": "{count} job",
  "queue.jobs.other": "{count} jobs",
  "queue.clearFinished": "Clear finished",
  "queue.empty": "The render queue is empty.",
  "queue.run": "Run render job",
  "queue.remove": "Remove render job",
  "timeline.editorAria": "Animation editor view",
  "timeline.timeline": "Timeline",
  "timeline.dopesheet": "Dopesheet",
  "timeline.graph": "Graph",
  "timeline.nla": "NLA",
  "timeline.goStart": "Go to start",
  "timeline.previousKey": "Previous keyframe",
  "timeline.nextKey": "Next keyframe",
  "timeline.goEnd": "Go to end",
  "timeline.frame": "Frame",
  "timeline.fps": "FPS",
  "timeline.addMarker": "Add Marker",
  "timeline.addKey": "Add Key",
  "timeline.markerPrompt": "Marker name",
  "timeline.markerDefault": "Marker {count}",
  "timeline.clipPrompt": "Animation clip name",
  "timeline.clipDefault": "Reusable Clip",
  "timeline.copyKeys": "Copy selected keyframes",
  "timeline.pasteKeys": "Paste keyframes at playhead",
  "timeline.duplicateKeys": "Duplicate selected keyframes",
  "timeline.deleteKeys": "Delete selected keyframes",
  "timeline.snap": "Snap",
  "timeline.step": "Step",
  "timeline.interpolationAria": "Selected keyframe interpolation",
  "timeline.interpolation.constant": "Constant",
  "timeline.interpolation.linear": "Linear",
  "timeline.interpolation.easeIn": "Ease In",
  "timeline.interpolation.easeOut": "Ease Out",
  "timeline.interpolation.easeInOut": "Ease In Out",
  "timeline.interpolation.bezier": "Bezier",
  "timeline.saveClip": "Save Clip",
  "timeline.clipAria": "Reusable animation clip",
  "timeline.clips": "Animation Clips",
  "timeline.applyClip": "Apply Clip",
  "timeline.addNla": "Add To NLA",
  "timeline.effectSelected": "FX: {name}",
  "timeline.moveEffectEarlier": "Move selected effect earlier",
  "timeline.moveEffectLater": "Move selected effect later",
  "timeline.moveEffectPlayhead": "Move selected effect to the playhead",
  "timeline.moveAt": "Move @",
  "timeline.trimStart": "Trim the selected effect start to the playhead",
  "timeline.trimEnd": "Trim the selected effect end to the playhead",
  "timeline.trimLeft": "Trim L",
  "timeline.trimRight": "Trim R",
  "timeline.duplicateEffect": "Duplicate selected effect",
  "timeline.copyEffect": "Copy selected effect",
  "timeline.pasteEffect": "Paste copied effect at the playhead",
  "timeline.disableEffect": "Disable selected effect",
  "timeline.enableEffect": "Enable selected effect",
  "timeline.disableFx": "Disable FX",
  "timeline.enableFx": "Enable FX",
  "timeline.priorityEarlier": "Move selected effect earlier in persisted priority order",
  "timeline.priorityLater": "Move selected effect later in persisted priority order",
  "timeline.priorityMinus": "Priority -",
  "timeline.priorityPlus": "Priority +",
  "timeline.copied": "Copied: {name}",
  "timeline.summary": "{selected} selected / {markers} markers / {clips} clips",
  "timeline.scrubberAria": "Timeline scrubber",
  "timeline.frameTitle": "Frame {frame}",
  "timeline.nlaEmpty": "Save a clip, select it, then add it to NLA.",
  "timeline.missingClip": "Missing clip",
  "timeline.missing": "Missing",
  "timeline.laneAria": "{label} lane",
  "timeline.disabledSuffix": "disabled",
  "timeline.dragMove": "{title}. Drag to move.",
  "timeline.trimItemStart": "Trim {name} start",
  "timeline.trimItemEnd": "Trim {name} end",
  "timeline.dragTrimStart": "Drag to trim effect start",
  "timeline.dragTrimEnd": "Drag to trim effect end",
  "history.moveKeys": "Move keyframes",
  "history.addMarker": "Add timeline marker",
  "history.saveClip": "Save animation clip",
  "history.applyClip": "Apply animation clip",
  "history.addNla": "Add NLA clip",
  "history.pasteKeys": "Paste keyframes",
  "history.duplicateKeys": "Duplicate keyframes",
  "history.deleteKeys": "Delete keyframes",
  "history.compressKeys": "Compress keyframe timing",
  "history.expandKeys": "Expand keyframe timing",
  "history.setInterpolation": "Set keyframe interpolation",
  "history.setGraphInterpolation": "Set graph interpolation",
  "history.toggleNla": "Toggle NLA clip",
  "inspector.title": "Inspector",
  "inspector.sky": "Sky",
  "inspector.preset": "Preset",
  "inspector.customColor": "Custom Color",
  "inspector.selectPrompt": "Select an object to edit its transform.",
  "inspector.character": "Character",
  "inspector.rig": "Rig",
  "inspector.boneId": "Bone ID",
  "inspector.boneRotation": "Bone Rotation",
  "inspector.addBoneKey": "Add Bone Keyframe",
  "inspector.post": "Post",
  "inspector.enablePost": "Enable post-processing",
  "inspector.bloom": "Bloom",
  "inspector.vignette": "Vignette",
  "inspector.saturation": "Saturation",
  "inspector.contrast": "Contrast",
  "inspector.grain": "Grain",
  "inspector.pixelate": "Pixelate",
  "inspector.type": "Type",
  "inspector.start": "Start",
  "inspector.duration": "Duration",
  "inspector.position": "Position",
  "inspector.rotation": "Rotation",
  "inspector.scale": "Scale",
  "inspector.deleteEffect": "Delete Effect",
  "inspector.invalidParameter": "Parameter value is invalid.",
  "inspector.parametersUnavailable": "Parameter controls are unavailable.",
  "inspector.parameterNote": "Values come from the effect schema. Parameter keyframes require schema 10.",
  "inspector.legacyParameters": "Preserved legacy parameters ({count})",
  "inspector.colorPicker": "{name} picker",
  "inspector.invalidLegacy": "Invalid legacy value: {value}",
  "inspector.minimum": "min {value}",
  "inspector.maximum": "max {value}",
  "inspector.stepValue": "step {value}",
  "inspector.defaultValue": "Default: {value}",
  "inspector.runtime.live": "Live preview",
  "inspector.runtime.export": "Offline export only",
  "inspector.runtime.stored": "Stored only (render support pending)",
  "inspector.keyframesSchema10": "Keyframes unavailable until schema 10.",
  "inspector.storedLegacy": "Stored legacy value: {value}",
  "inspector.restoreDefault": "Restore valid default",
  "inspector.world": "World",
  "inspector.source": "Source",
  "inspector.level": "Level",
  "inspector.found": "found",
  "inspector.missing": "missing",
  "inspector.spawn": "Spawn",
  "inspector.dimension": "Dimension",
  "inspector.chunks": "Chunks",
  "inspector.blocks": "Blocks",
  "inspector.unknown": "Unknown",
  "inspector.regionFiles.one": "{count} region file",
  "inspector.regionFiles.other": "{count} region files",
  "inspector.demoTerrain": "Demo terrain is active until a Minecraft world folder is scanned.",
  "inspector.name": "Name",
  "inspector.visible": "Visible",
  "inspector.hidden": "Hidden",
  "inspector.locked": "Locked",
  "inspector.unlocked": "Unlocked",
  "inspector.addKeyframe": "Add Keyframe",
  "inspector.lookThrough": "Look Through",
  "inspector.cameraPresets": "Camera Presets",
  "inspector.addCameraPreset": "Add Camera Preset",
  "inspector.poseLibrary": "Pose Library",
  "inspector.applyPose": "Apply Pose",
  "inspector.animationPresets": "Animation Presets",
  "inspector.applyAnimation": "Apply Animation Preset",
  "inspector.rigSkin": "Rig And Skin",
  "inspector.rigPreset": "Rig Preset",
  "inspector.placeholder": "placeholder",
  "inspector.bones": "Bones",
  "inspector.arms": "Arms",
  "inspector.skin": "Skin",
  "inspector.resolution": "Resolution",
  "inspector.model": "Model",
  "inspector.valid": "Valid",
  "inspector.yes": "yes",
  "inspector.no": "no",
  "inspector.fallbackColors": "fallback colors",
  "inspector.presetAction": "{action}: {name}",
  "lighting.title": "Lighting Studio",
  "lighting.closeAria": "Close Lighting Studio",
  "lighting.moods": "Mood Presets",
  "lighting.sunAmbient": "Sun & Ambient",
  "lighting.sunIntensity": "Sun intensity",
  "lighting.ambientIntensity": "Ambient intensity",
  "lighting.sunColor": "Sun color",
  "lighting.ambientColor": "Ambient color",
  "lighting.sunDirection": "Sun direction",
  "lighting.shadows": "Shadows",
  "lighting.atmosphere": "Atmosphere",
  "lighting.fogColor": "Fog color",
  "lighting.fogDensity": "Fog density",
  "lighting.timeOfDay": "Time of day",
  "lighting.animateTime": "Animate time of day",
  "lighting.dayLength": "Day length (frames)",
  "lighting.keyframeAt": "Keyframe at {frame}",
  "lighting.environmentKeys.one": "{count} environment key",
  "lighting.environmentKeys.other": "{count} environment keys",
  "lighting.shaderPost": "Shader & Post",
  "lighting.enablePost": "Enable post-processing",
  "lighting.bloom": "Bloom",
  "lighting.vignette": "Vignette",
  "lighting.grain": "Grain",
  "lighting.chromatic": "Chromatic aberration",
  "lighting.exposure": "Exposure",
  "lighting.contrast": "Contrast",
  "lighting.materials": "Minecraft Materials",
  "lighting.filtering": "Texture filtering",
  "lighting.nearest": "Nearest (Minecraft)",
  "lighting.linear": "Linear",
  "lighting.defaultMaterial": "Default material",
  "lighting.biomeTint": "Biome color tint",
  "lighting.biomePreset": "Biome tint preset",
  "lighting.grass": "Grass",
  "lighting.foliage": "Foliage",
  "lighting.water": "Water",
  "lighting.resourcePacks": "Resource Packs",
  "lighting.importZip": "Import ZIP",
  "lighting.importFolder": "Import Folder",
  "lighting.resetTextures": "Reset Textures",
  "lighting.noResourcePack": "No resource pack imported.",
  "lighting.packSummary": "pack_format {format} / {count} block textures / {source}",
  "lighting.apply": "Apply",
  "lighting.removePack": "Remove {name}",
  "dopesheet.empty": "Add keyframes to populate the dopesheet.",
  "dopesheet.ariaLabel": "Animation dopesheet",
  "graph.empty": "Select a keyframe to inspect its property curves.",
  "graph.interpolation": "Interpolation",
  "graph.bezierPlaceholder": "Bezier Placeholder",
  "graph.curvesAria": "{property} animation curves",
  "app.ready": "Ready. Professional animation, resource-pack, and lighting systems loaded.",
  "app.confirmAutosave": "A MineMotion autosave was found in this browser. Restore it?",
  "app.autosaveBackupRestored": "Primary autosave was invalid; the retained backup was restored.",
  "app.autosaveRestored": "Autosaved project restored from browser storage.",
  "app.recoveryRetained": "{message} Stored recovery data was retained.",
  "app.recoveryFailed": "Autosave recovery failed; stored recovery data was retained.",
  "app.autosaved": "Autosaved {name} to browser storage.",
  "app.autosaveFailedDetail": "Autosave failed: {message}",
  "app.autosaveFailed": "Autosave failed.",
  "app.confirmDiscard": "Current project has unsaved changes. Continue?",
  "app.newProject": "New project created.",
  "app.templateLoaded": "Template loaded: {name}.",
  "app.projectSaved": "Project saved as {filename}.",
  "app.legacyExported": "Legacy schema 9 project exported as {filename}.",
  "app.legacyVfxUnsupported": "Project contains native VFX data that schema 9 cannot represent.",
  "app.projectLoaded": "Loaded project {name}.",
  "app.projectLoadFailed": "Could not load project.",
  "app.worldScanning": "Scanning Minecraft world folder.",
  "app.worldScanned": "Scanned {name}.",
  "app.worldScanComplete": "World scan complete: {name}, {dimensions} region files.",
  "app.worldScanFailed": "Could not scan world folder.",
  "app.chooseWorld": "Choose a Minecraft world folder before importing chunks.",
  "app.worldPreparing": "Preparing chunk import.",
  "app.worldImported": "Imported {chunks} chunks and {blocks} blocks from {name}.",
  "app.worldImportFailed": "Minecraft chunk import failed.",
  "app.worldCancel": "World import cancellation requested.",
  "app.worldFocused": "Viewport focused on imported world.",
  "app.worldUnloaded": "Imported world unloaded; demo terrain restored.",
  "app.addedEntity": "Added {name}.",
  "app.objImportedWarning": "Imported OBJ with warning: {warning}",
  "app.objImportedWarnings": "Imported OBJ {name} with {count} technical warnings.",
  "app.objImported": "Imported OBJ {name}.",
  "app.objFailed": "Could not import OBJ.",
  "app.selectCharacterSkin": "Select a character before importing a skin.",
  "app.skinImported": "Imported skin {name} ({width}x{height}, {model}).",
  "app.skinInvalid": "Skin {name} imported but invalid; fallback colors remain active.",
  "app.skinFailed": "Could not import skin.",
  "app.skinReset": "Skin reset to fallback Minecraft colors.",
  "app.blockbenchImported": "Imported Blockbench model {name}: {cubes} cubes, {groups} groups.",
  "app.blockbenchFailed": "Could not import Blockbench model.",
  "app.entityLocked": "{name} is locked.",
  "app.effectFinalFrame": "Move before the final project frame to add an effect.",
  "app.effectAddFailed": "Could not add cinematic effect.",
  "app.effectAdded": "Added effect {name} at frame {frame}.",
  "app.customVfxUnavailable": "Custom VFX package {id} is missing or disabled.",
  "app.customVfxAddFailed": "Could not add custom VFX.",
  "app.vfxRegistryWarnings": "{count} installed VFX package records could not be loaded safely.",
  "app.customVfxAdded": "Added custom VFX {name} at frame {frame}.",
  "app.effectEditFailed": "Effect timeline edit failed.",
  "app.effectUnchanged": "Effect timeline already has that value.",
  "app.postPreset": "Post-processing preset applied: {name}.",
  "app.postUpdated": "Post-processing updated.",
  "app.previewToggled": "Render preview toggled.",
  "app.barsToggled": "Cinematic bars toggled.",
  "app.ffmpegChanged": "FFmpeg executable changed. Run detection again.",
  "app.ffmpegDetecting": "Detecting FFmpeg...",
  "app.jobAdded": "Added {name} to the render queue.",
  "app.exportInvalid": "Export settings are invalid.",
  "app.captureFrame": "Capturing current viewport frame.",
  "app.exported": "Exported {filename}.",
  "app.pngFailed": "PNG export failed.",
  "app.sequencePreparing": "Preparing PNG sequence export.",
  "app.sequenceFailed": "PNG sequence export failed.",
  "app.webmRecording": "Recording viewport canvas as WebM.",
  "app.recordingFrame": "Recording frame {frame} of {total}.",
  "app.exportedSize": "Exported {filename} at {width}x{height}.",
  "app.webmFailed": "WebM export failed.",
  "app.wavMixing": "Mixing project audio to WAV.",
  "app.wavFailed": "WAV export failed.",
  "app.exportCancel": "Export cancellation requested.",
  "app.sfxUnsupported": "Unsupported SFX file type. Use wav, mp3, or ogg audio.",
  "app.sfxImported": "Imported SFX {name}.",
  "app.sfxFailed": "Could not import SFX.",
  "app.sfxAdded": "Added placeholder SFX {name}.",
  "app.selectDuplicate": "Select an object before duplicating.",
  "app.duplicated": "Duplicated {name}.",
  "app.boneUpdated": "Updated {bone} rotation.",
  "app.boneKey": "Bone keyframe added for {bone} at frame {frame}.",
  "app.poseReset": "Rig pose reset.",
  "app.poseMirrored": "Rig pose mirrored left/right.",
  "app.posePrompt": "Pose name",
  "app.poseDefault": "{name} Pose",
  "app.poseSaved": "Saved pose {name}.",
  "app.rigChanged": "Rig preset changed to {name}.",
  "app.selectDelete": "Select an object before deleting.",
  "app.deleted": "Deleted {name}.",
  "app.selectKeyframe": "Select a character, camera, light, or OBJ before keyframing.",
  "app.notKeyframeable": "Selected object is not keyframeable.",
  "app.transformKey": "Transform keyframe added for {name} at frame {frame}.",
  "app.skyChanged": "Sky preset set to {preset}.",
  "app.lightingMood": "Lighting mood applied: {name}.",
  "app.lightingUpdated": "Lighting updated.",
  "app.materialsUpdated": "Minecraft material settings updated.",
  "app.resourcePackImported": "Imported resource pack {name}: {count} block textures.",
  "app.resourceZipFailed": "Could not import resource pack ZIP.",
  "app.resourceFolderFailed": "Could not import resource pack folder.",
  "app.resourceApplied": "Resource pack applied.",
  "app.resourceReset": "Resource pack textures reset.",
  "app.resourceRemoved": "Resource pack removed.",
  "app.environmentKey": "Environment keyframe added at frame {frame}.",
  "app.projectSettingsUpdated": "Project settings updated.",
  "app.selectCamera": "Select a scene camera first.",
  "app.cameraMoved": "Viewport moved to selected camera position.",
  "app.cameraReset": "Viewport camera reset to the first scene camera.",
  "app.cameraPreset": "Camera preset applied: {name}.",
  "app.poseApplied": "Pose applied: {name}.",
  "app.animationPreset": "Animation preset applied: {name}.",
  "app.nothingUndo": "Nothing to undo.",
  "app.undo": "Undo.",
  "app.nothingRedo": "Nothing to redo.",
  "app.redo": "Redo.",
  "app.pluginState": "{state} plugin {id}.",
  "status.selected": "Selected: {name}",
  "status.frame": "Frame: {frame}",
  "status.fps": "FPS: {fps}",
  "status.unsaved": "Unsaved",
  "status.saved": "Saved",
  "status.post": "Post: {preset}",
  "status.lighting": "Lighting: {preset}",
  "status.effects": "FX: {count}",
  "status.audio": "SFX: {count}",
  "status.export": "Export: {width}x{height}",
  "status.renderPreview": "Render Preview",
  "status.viewport": "Viewport",
  "status.world": "World: {name}",
  "status.worldDemo": "World: demo",
  "status.character": "Character",
  "viewport.ariaLabel": "3D viewport",
  "viewport.perspective": "Perspective",
  "viewport.activeCamera": "Active camera: {name}",
  "viewport.orbit": "Orbit: drag",
  "viewport.pan": "Pan: right drag",
  "viewport.zoom": "Zoom: wheel",
  "viewport.importedChunks.one": "{count} imported chunk",
  "viewport.importedChunks.other": "{count} imported chunks",
  "format.minute.short": "min",
  "format.second.short": "s",
  "format.effects.one": "{count} effect",
  "format.effects.other": "{count} effects"
} as const);

export type TranslationKey = keyof typeof EN_TRANSLATIONS;
export type TranslationCatalog = Readonly<Record<TranslationKey, string>>;
