import type { TranslationCatalog } from "./en";

export const FR_TRANSLATIONS = Object.freeze({
  "common.close": "Fermer",
  "common.enabled": "Activé",
  "common.disabled": "Désactivé",
  "common.none": "Aucun",
  "common.low": "Faible",
  "common.medium": "Moyenne",
  "common.high": "Élevée",
  "topbar.mainActions": "Actions principales",
  "topbar.newProject": "Nouveau projet",
  "topbar.templates": "Modèles",
  "topbar.openWorld": "Ouvrir un monde",
  "topbar.saveProject": "Enregistrer le projet",
  "topbar.loadProject": "Charger un projet",
  "topbar.addCharacter": "Ajouter un personnage",
  "topbar.addCamera": "Ajouter une caméra",
  "topbar.importObj": "Importer un OBJ",
  "topbar.pause": "Pause",
  "topbar.play": "Lecture",
  "topbar.settings": "Paramètres",
  "topbar.plugins": "Extensions",
  "topbar.commands": "Commandes",
  "topbar.export": "Exporter",
  "topbar.rigStudio": "Studio de rig",
  "topbar.lighting": "Éclairage",
  "topbar.vfxStudio": "Studio VFX",
  "topbar.help": "Aide",
  "topbar.viewport": "Vue 3D",
  "topbar.renderPreview": "Aperçu du rendu",
  "settings.title": "Paramètres",
  "settings.app": "Paramètres de l’application",
  "settings.language": "Langue",
  "settings.language.system": "Langue du système",
  "settings.language.english": "Anglais",
  "settings.language.french": "Français",
  "settings.autosaveEnabled": "Sauvegarde automatique activée",
  "settings.autosaveInterval": "Intervalle de sauvegarde automatique (s)",
  "settings.defaultFps": "IPS par défaut",
  "settings.defaultDuration": "Durée par défaut",
  "settings.defaultNamePattern": "Modèle de nom par défaut",
  "settings.viewport": "Vue 3D",
  "settings.backgroundColor": "Couleur d’arrière-plan",
  "settings.showGrid": "Afficher la grille",
  "settings.gridSize": "Taille de la grille",
  "settings.orbitSpeed": "Vitesse d’orbite",
  "settings.renderQuality": "Qualité du rendu",
  "settings.editor": "Éditeur",
  "settings.theme": "Thème",
  "settings.theme.dark": "Sombre",
  "settings.theme.lightPlaceholder": "Clair (provisoire)",
  "settings.uiScale": "Échelle de l’interface",
  "settings.snapToGrid": "Aligner sur la grille",
  "settings.transformStep": "Pas de déplacement",
  "settings.rotationStep": "Pas de rotation",
  "settings.minecraft": "Minecraft",
  "settings.defaultSky": "Ciel par défaut",
  "settings.blockPaletteStyle": "Style de palette de blocs",
  "settings.palette.classic": "Classique",
  "settings.palette.muted": "Atténuée",
  "settings.palette.nether": "Nether",
  "settings.defaultTerrainSize": "Taille de terrain par défaut",
  "settings.resourcePackPath": "Chemin du pack de ressources",
  "settings.project": "Paramètres du projet",
  "settings.projectName": "Nom du projet",
  "settings.fps": "IPS",
  "settings.durationFrames": "Durée en images",
  "settings.terrainPreset": "Préréglage de terrain",
  "settings.terrain.demo": "Démo",
  "settings.terrain.flat": "Plat",
  "settings.terrain.nether": "Nether",
  "settings.resolutionPreset": "Préréglage de résolution",
  "settings.resolution.custom": "Personnalisée",
  "settings.author": "Auteur",
  "settings.notes": "Notes",
  "settings.plugins": "Extensions",
  "settings.plugins.enabled": "Activer le registre d’extensions intégrées",
  "settings.plugins.experimental": "Autoriser les manifestes d’extensions expérimentales",
  "settings.plugins.folder": "Chemin du dossier des extensions",
  "settings.plugins.executionDisabled": "L’exécution de JavaScript provenant d’extensions externes est désactivée dans cette version.",
  "help.ariaLabel": "Aide de MineMotion",
  "help.quickStart": "Prise en main",
  "help.loadSampleScene": "Charger la scène d’exemple",
  "help.orbit": "Faites glisser dans la vue 3D pour orbiter, utilisez le bouton droit pour déplacer la vue et la molette pour zoomer.",
  "help.select": "Sélectionnez les objets dans la vue 3D ou l’Outliner.",
  "help.transforms": "Modifiez les transformations dans l’Inspecteur.",
  "help.keyframes": "Ajoutez une image clé, passez à une autre image, modifiez l’objet, puis ajoutez-en une autre.",
  "help.effects": "Ajoutez des effets cinématiques depuis le panneau Effets à l’image courante.",
  "help.postProcessing": "Utilisez les préréglages de post-traitement pour obtenir un rendu cinématique.",
  "help.renderPreview": "Activez l’aperçu du rendu pour voir les bandes, les post-effets et le cadrage de la caméra active.",
  "help.sfx": "Importez un effet sonore ou ajoutez-en un provisoire à la timeline.",
  "help.play": "Utilisez Lecture pour prévisualiser l’animation linéaire.",
  "help.worldImport": "L’import de monde analyse les dossiers de mondes Java réels et peut charger les chunks sélectionnés.",
  "help.save": "Enregistrez les projets sous forme de paquets `.minemotion` ; l’export historique `.mmsproj` se trouve dans Exporter.",
  "help.shortcuts": "Raccourcis clavier",
  "help.shortcut.commands": "Ctrl+P — ouvrir la palette de commandes",
  "help.shortcut.save": "Ctrl+S — enregistrer le projet actuel",
  "help.shortcut.undo": "Ctrl+Z / Ctrl+Y — annuler / rétablir",
  "help.shortcut.duplicate": "Ctrl+D — dupliquer l’objet ou l’effet sélectionné",
  "help.shortcut.delete": "Suppr — supprimer l’objet ou l’effet sélectionné",
  "help.shortcut.play": "Espace — lire ou mettre en pause la timeline",
  "outliner.title": "Outliner",
  "outliner.scene": "Scène",
  "outliner.characters": "Personnages",
  "outliner.cameras": "Caméras",
  "outliner.objAssets": "Objets OBJ",
  "outliner.lights": "Éclairages",
  "outliner.demoWorld": "Monde de démonstration",
  "outliner.world.scanned": "monde analysé",
  "outliner.world.generated": "terrain généré",
  "outliner.chunks.one": "{count} chunk",
  "outliner.chunks.other": "{count} chunks",
  "outliner.noObj": "Aucun objet OBJ importé.",
  "outliner.bone": "os",
  "outliner.entity.character": "personnage",
  "outliner.entity.camera": "caméra",
  "outliner.entity.object": "objet",
  "outliner.entity.light": "éclairage",
  "commands.ariaLabel": "Palette de commandes",
  "commands.searchPlaceholder": "Saisissez une commande…",
  "commands.group.project": "Projet",
  "commands.group.scene": "Scène",
  "commands.group.timeline": "Timeline",
  "commands.group.view": "Vue",
  "commands.group.settings": "Paramètres",
  "commands.group.plugins": "Extensions",
  "commands.group.effects": "Effets",
  "commands.group.render": "Rendu",
  "commands.group.post": "Post-traitement",
  "commands.newProject": "Nouveau projet",
  "commands.saveProject": "Enregistrer le projet",
  "commands.loadProject": "Charger un projet",
  "commands.savePackage": "Enregistrer le paquet .minemotion",
  "commands.exportLegacy": "Exporter au format historique .mmsproj",
  "commands.addCharacter": "Ajouter un personnage",
  "commands.addCamera": "Ajouter une caméra",
  "commands.importObj": "Importer un OBJ",
  "commands.duplicateSelected": "Dupliquer l’objet sélectionné",
  "commands.deleteSelected": "Supprimer l’objet sélectionné",
  "commands.openSettings": "Ouvrir les paramètres",
  "commands.openPlugins": "Ouvrir le gestionnaire d’extensions",
  "commands.applySky": "Appliquer le ciel : {sky}",
  "commands.sky.day": "Jour",
  "commands.sky.sunset": "Crépuscule",
  "commands.sky.night": "Nuit",
  "commands.toggleTimeline": "Lire ou mettre en pause la timeline",
  "commands.resetCamera": "Réinitialiser la caméra de la vue 3D",
  "commands.addKeyframe": "Ajouter une image clé",
  "commands.effect.lightningStrike": "Ajouter un éclair",
  "commands.effect.impactFrame": "Ajouter une image d’impact",
  "commands.effect.cameraShake": "Ajouter une secousse de caméra",
  "commands.effect.flash": "Ajouter un flash",
  "commands.effect.speedLines": "Ajouter des lignes de vitesse",
  "commands.effect.shockwave": "Ajouter une onde de choc",
  "commands.effect.glowBurst": "Ajouter une explosion lumineuse",
  "commands.togglePreview": "Activer ou désactiver l’aperçu du rendu",
  "commands.toggleBars": "Activer ou désactiver les bandes cinématiques",
  "commands.openExport": "Ouvrir le panneau d’export",
  "commands.exportFrame": "Exporter l’image courante en PNG",
  "commands.exportSequence": "Exporter une séquence PNG en ZIP",
  "commands.post.cinematicWarm": "Post-traitement : Cinématique chaude",
  "commands.post.darkHorror": "Post-traitement : Horreur sombre",
  "commands.post.animeImpact": "Post-traitement : Impact animé",
  "commands.post.retroPixel": "Post-traitement : Pixel rétro",
  "commands.undo": "Annuler",
  "commands.redo": "Rétablir",
  "templates.ariaLabel": "Nouveau projet à partir d’un modèle",
  "templates.title": "Nouveau projet à partir d’un modèle",
  "templates.category.starter": "Prise en main",
  "templates.category.animation": "Animation",
  "templates.category.cinematic": "Cinématique",
  "templates.category.mood": "Ambiance",
  "templates.emptyScene.name": "Scène vide",
  "templates.emptyScene.description": "Grille, caméra et ciel par défaut, sans terrain ni personnage.",
  "templates.flatWorld.name": "Monde Minecraft plat",
  "templates.flatWorld.description": "Monde de test plat en herbe et terre avec une caméra et un éclairage.",
  "templates.characterAnimation.name": "Test d’animation de personnage",
  "templates.characterAnimation.description": "Un personnage avec des images clés de mouvement sur 120 images.",
  "templates.cinematicCamera.name": "Test de caméra cinématique",
  "templates.cinematicCamera.description": "Terrain et travelling avant animé par images clés.",
  "templates.sunset.name": "Vitrine au crépuscule",
  "templates.sunset.description": "Ciel chaud, terrain, personnage et caméra cinématique.",
  "templates.nether.name": "Ambiance du Nether",
  "templates.nether.description": "Ciel inspiré du Nether, palette de terrain sombre et faible éclairage.",
  "plugins.ariaLabel": "Gestionnaire d’extensions",
  "plugins.title": "Gestionnaire d’extensions",
  "plugins.securityNotice": "L’exécution de JavaScript provenant d’extensions externes est désactivée dans cette version. Les extensions intégrées sont des modules TypeScript inclus ; les manifestes externes ne doivent pas être exécutés sans un futur bac à sable.",
  "plugins.builtin": "intégrée",
  "plugins.externalManifest": "manifeste externe",
  "effects.title": "Effets",
  "effects.library": "Bibliothèque",
  "effects.search": "Rechercher des VFX",
  "effects.searchAria": "Rechercher des préréglages VFX",
  "effects.sourceAria": "Source des préréglages VFX",
  "effects.source.all": "Tous {count}",
  "effects.source.builtin": "Intégrés {count}",
  "effects.source.custom": "Personnalisés {count}",
  "effects.categoryAria": "Filtrer la catégorie VFX",
  "effects.allCategories": "Toutes les catégories",
  "effects.tagAria": "Ajouter un filtre d’étiquette VFX",
  "effects.addTag": "Ajouter une étiquette",
  "effects.favorites": "Favoris",
  "effects.activeTagsAria": "Filtres d’étiquettes VFX actifs",
  "effects.recent": "Récents",
  "effects.results.one": "{count} résultat",
  "effects.results.other": "{count} résultats",
  "effects.previewPending": "Aperçu en attente",
  "effects.builtinMaturity": "Intégré / {maturity}",
  "effects.customSpace": "Personnalisé / {space}",
  "effects.favorite.add": "Ajouter {name} aux favoris",
  "effects.favorite.remove": "Retirer {name} des favoris",
  "effects.emptyCustom": "Aucun paquet VFX personnalisé n’est installé.",
  "effects.emptyFiltered": "Aucun préréglage VFX ne correspond à ces filtres.",
  "effects.scene": "Effets de la scène",
  "effects.projectCount.one": "{count} effet dans ce projet.",
  "effects.projectCount.other": "{count} effets dans ce projet.",
  "effects.sceneAria": "Effets de la scène",
  "effects.sourceMissing": "{state} / paquet source manquant (recette intégrée conservée)",
  "effects.sourceDisabled": "{state} / paquet source désactivé (recette intégrée conservée)",
  "effects.sourceVersionChanged": "{state} / version du paquet source modifiée (recette intégrée conservée)",
  "effects.addFromLibrary": "Ajoutez un effet depuis la bibliothèque.",
  "effects.post": "Post-traitement",
  "effects.renderPreview": "Aperçu du rendu",
  "effects.leavePreview": "Quitter l’aperçu",
  "effects.enterPreview": "Ouvrir l’aperçu",
  "effects.hideBars": "Masquer les bandes",
  "effects.showBars": "Afficher les bandes",
  "effects.sfx": "Effets sonores",
  "effects.importSfx": "Importer un effet sonore",
  "effects.audioCount.one": "{count} piste audio sur la timeline.",
  "effects.audioCount.other": "{count} pistes audio sur la timeline.",
  "vfx.title": "Workspace VFX",
  "vfx.closeAria": "Fermer le workspace VFX",
  "vfx.safeSource": "Source de brouillon sûre",
  "vfx.stableBuiltin": "Effet natif intégré stable",
  "vfx.derive": "Dériver une copie de brouillon",
  "vfx.newBlank": "Nouveau brouillon vide",
  "vfx.packageAuthor": "Auteur du paquet",
  "vfx.license": "Licence SPDX",
  "vfx.exportPackage": "Exporter en .minemotion-vfx",
  "vfx.inspectPackage": "Inspecter un paquet",
  "vfx.safety": "Données déclaratives uniquement. Le JavaScript, les extensions exécutables et les shaders sans restrictions ne sont pas acceptés.",
  "vfx.draftSettings": "Paramètres du brouillon",
  "vfx.durationFrames": "Durée (images)",
  "vfx.targetEntity": "Entité cible",
  "vfx.targetEntityPlaceholder": "Identifiant d’entité facultatif",
  "vfx.targetBone": "Os cible",
  "vfx.targetBonePlaceholder": "Identifiant d’os facultatif",
  "vfx.previewQuality": "Qualité de l’aperçu",
  "vfx.exportQuality": "Qualité de l’export",
  "vfx.quality.draft": "Brouillon",
  "vfx.quality.medium": "Moyenne",
  "vfx.quality.high": "Élevée",
  "vfx.quality.final": "Finale",
  "vfx.previewAlt": "Aperçu de {name}",
  "vfx.work": "{primitives} primitives / {particles} particules / {segments} segments",
  "vfx.itemEditor": "Éditeur d’élément",
  "vfx.label": "Libellé",
  "vfx.color": "Couleur",
  "vfx.tint": "Teinte",
  "vfx.primaryValue": "Valeur principale",
  "vfx.modifierScope": "{kind} s’applique à tous les éléments actifs placés au-dessus.",
  "vfx.selectItem": "Sélectionnez un élément de la pile pour le modifier.",
  "vfx.stack": "Pile ({count}/16)",
  "vfx.add": "Ajouter",
  "vfx.stackAria": "Pile de création VFX",
  "vfx.moveUp": "Monter {name}",
  "vfx.moveDown": "Descendre {name}",
  "vfx.duplicate": "Dupliquer {name}",
  "vfx.enable": "Activer {name}",
  "vfx.disable": "Désactiver {name}",
  "vfx.delete": "Supprimer {name}",
  "vfx.emptyStack": "Ajoutez une primitive, un émetteur ou un modificateur restreint.",
  "vfx.report": "Rapport du paquet avant installation",
  "vfx.packagePreviewAlt": "Aperçu du paquet {name}",
  "vfx.package": "Paquet",
  "vfx.authorLicense": "Auteur / licence",
  "vfx.installReadiness": "État de préparation",
  "vfx.ready": "Prêt",
  "vfx.missingDependencies": "Dépendances obligatoires manquantes",
  "vfx.runtimeWork": "Charge d’exécution",
  "vfx.assets": "Ressources",
  "vfx.packageLicense": "licence du paquet",
  "vfx.dependencies": "Dépendances",
  "vfx.permissions": "Autorisations",
  "vfx.optional": "facultatif",
  "vfx.dependency.satisfied": "satisfaite",
  "vfx.dependency.missing": "manquante",
  "vfx.dependency.version-mismatch": "version incompatible",
  "vfx.permission.asset-textures": "Utiliser les textures et sprites fournis par le pack.",
  "vfx.permission.asset-audio": "Utiliser l’audio fourni par le pack pendant l’aperçu et l’export.",
  "vfx.permission.asset-models": "Utiliser les données de modèle prises en charge fournies par le pack.",
  "vfx.permission.restricted-shader-templates": "Utiliser uniquement les paramètres validés des modèles de shader intégrés.",
  "vfx.inspectionOnly": "Inspection uniquement. Ce paquet n’a pas été installé, activé ni écrit dans le stockage local.",
  "vfx.installedInspection": "Inspection en lecture seule d’un paquet local déjà installé.",
  "vfx.updateInstalled": "Mettre à jour le paquet installé",
  "vfx.installLocally": "Installer le paquet localement",
  "vfx.installedPackages": "Paquets personnalisés installés ({count}/32)",
  "vfx.inspect": "Inspecter",
  "vfx.enableAction": "Activer",
  "vfx.disableAction": "Désactiver",
  "vfx.uninstall": "Désinstaller",
  "vfx.noInstalled": "Aucun paquet VFX personnalisé n’est installé localement.",
  "vfx.message.blank": "Brouillon déclaratif vide prêt.",
  "vfx.message.noChange": "Aucune modification du brouillon VFX.",
  "vfx.message.authoringInvalid": "La modification du brouillon VFX n’est pas valide. Vérifiez les limites des champs puis réessayez.",
  "vfx.message.chooseBuiltin": "Choisissez d’abord un effet natif intégré stable.",
  "vfx.message.derived": "Une copie de brouillon personnalisée a été créée sans modifier {name}.",
  "vfx.message.deriveFailed": "Impossible de dériver le préréglage sélectionné.",
  "vfx.message.compileFailed": "Le brouillon VFX ne peut pas être compilé dans les limites du schéma et des budgets pris en charge.",
  "vfx.message.exported": "Paquet déterministe {filename} exporté.",
  "vfx.message.exportFailed": "Impossible d’exporter le paquet VFX.",
  "vfx.message.inspected": "{name} inspecté. Rien n’a été installé ni modifié.",
  "vfx.message.inspectFailed": "Impossible d’inspecter le paquet VFX.",
  "vfx.message.storageFailed": "Le stockage local des paquets VFX est plein ou indisponible ; aucune modification du registre n’a été conservée.",
  "vfx.message.installed": "{name} installé localement.",
  "vfx.message.updated": "{name} mis à jour localement.",
  "vfx.message.installFailed": "Impossible d’installer le paquet VFX.",
  "vfx.message.state": "{id} : {state}.",
  "vfx.message.stateFailed": "Impossible de modifier l’état du paquet VFX.",
  "vfx.message.confirmUninstall": "Désinstaller le paquet VFX local {id} ?",
  "vfx.message.uninstalled": "{id} désinstallé localement.",
  "vfx.message.uninstallFailed": "Impossible de désinstaller le paquet VFX.",
  "vfx.message.inspectingInstalled": "Inspection du paquet installé {id}.",
  "world.title": "Import de monde",
  "world.ariaLabel": "Import de monde",
  "world.folder": "Dossier du monde",
  "world.chooseFolder": "Choisir un dossier",
  "world.focus": "Cadrer le monde",
  "world.unload": "Décharger",
  "world.info.folder": "Dossier",
  "world.info.level": "Niveau",
  "world.info.dataVersion": "Version des données",
  "world.info.spawn": "Point d’apparition",
  "world.unknown": "inconnu",
  "world.scanPrompt": "Sélectionnez un dossier de monde Minecraft afin d’analyser `level.dat` et les fichiers de région `.mca`.",
  "world.selection": "Sélection à importer",
  "world.dimension": "Dimension",
  "world.dimension.overworld": "Monde normal",
  "world.dimension.nether": "Nether",
  "world.dimension.end": "End",
  "world.centerX": "Chunk central X",
  "world.centerZ": "Chunk central Z",
  "world.radius": "Rayon",
  "world.maxChunks": "Nombre maximal de chunks",
  "world.maxRegions": "Nombre maximal de régions",
  "world.maxSections": "Nombre maximal de sections",
  "world.showBorders": "Afficher les bordures des chunks",
  "world.showOrigin": "Afficher l’origine du monde",
  "world.embedCache": "Intégrer le cache des chunks importés au projet",
  "world.dimensions": "Dimensions",
  "world.regions.one": "{count} région",
  "world.regions.other": "{count} régions",
  "world.estimatedChunks.one": "{count} chunk estimé",
  "world.estimatedChunks.other": "{count} chunks estimés",
  "world.noScan": "Aucun dossier analysé pour le moment.",
  "world.selectedRegions.one": "La dimension sélectionnée contient {count} fichier de région.",
  "world.selectedRegions.other": "La dimension sélectionnée contient {count} fichiers de région.",
  "world.runImport": "Lancer l’import",
  "world.importChunks": "Importer les chunks",
  "world.cancel": "Annuler",
  "world.chunks": "Chunks",
  "world.blocks": "Blocs",
  "world.unknownBlocks": "Inconnus",
  "world.warnings": "Avertissements",
  "world.status.idle": "Inactif",
  "world.status.scanning": "Analyse",
  "world.status.reading-level": "Lecture des métadonnées du monde",
  "world.status.reading-regions": "Lecture des régions",
  "world.status.reading-chunks": "Lecture des chunks",
  "world.status.meshing": "Construction de la géométrie",
  "world.status.complete": "Terminé",
  "world.status.cancelled": "Annulé",
  "world.status.error": "Erreur",
  "world.progress.idle": "Aucun import de monde en cours.",
  "world.progress.scanning": "Analyse du dossier de monde sélectionné.",
  "world.progress.reading-level": "Lecture des métadonnées level validées.",
  "world.progress.reading-regions": "Lecture des fichiers de région sélectionnés.",
  "world.progress.reading-chunks": "Import des chunks Minecraft dans les limites définies.",
  "world.progress.meshing": "Construction de la géométrie déterministe des chunks.",
  "world.progress.complete": "Import du monde terminé.",
  "world.progress.cancelled": "Import du monde annulé.",
  "world.progress.error": "L’import du monde s’est arrêté avec une erreur.",
  "rig.title": "Studio de rig",
  "rig.closeAria": "Fermer le studio de rig",
  "rig.selectedCharacter": "Personnage sélectionné",
  "rig.selectPrompt": "Ajoutez ou sélectionnez d’abord un personnage.",
  "rig.poseLibrary": "Bibliothèque de poses",
  "rig.animationPresets": "Préréglages d’animation",
  "rig.blockbench": "Blockbench",
  "rig.importBlockbench": "Importer un modèle Blockbench",
  "rig.noBlockbench": "Aucun fichier .bbmodel importé pour le moment.",
  "rig.modelCounts": "{cubes} cubes / {groups} groupes / {textures} textures",
  "rig.skin": "Skin",
  "rig.fallbackColors": "couleurs de remplacement",
  "rig.resolution": "Résolution",
  "rig.model": "Modèle",
  "rig.status": "État",
  "rig.valid": "valide",
  "rig.invalid": "invalide",
  "rig.importSkin": "Importer un skin",
  "rig.resetSkin": "Réinitialiser le skin",
  "rig.savePose": "Enregistrer la pose actuelle",
  "rig.mirrorPose": "Inverser la pose",
  "rig.resetPose": "Réinitialiser la pose",
  "export.title": "Export de production",
  "export.ariaLabel": "Export de production",
  "export.output": "Sortie",
  "export.outputName": "Nom de la sortie",
  "export.format": "Format",
  "export.group.browserDesktop": "Navigateur et application de bureau",
  "export.group.ffmpeg": "Application de bureau + FFmpeg installé par l’utilisateur",
  "export.format.pngFrame": "Image courante en PNG",
  "export.format.pngSequence": "Séquence PNG en ZIP",
  "export.format.webm": "Vidéo WebM (vidéo uniquement)",
  "export.format.wav": "Mixage audio WAV",
  "export.format.package": "Paquet .minemotion",
  "export.format.audioMetadata": "Métadonnées audio JSON",
  "export.format.mp4H264": "MP4 H.264",
  "export.format.mp4H265": "MP4 H.265",
  "export.format.prores": "MOV ProRes",
  "export.format.mp3": "Audio MP3",
  "export.startFrame": "Première image",
  "export.endFrame": "Dernière image",
  "export.fps": "IPS",
  "export.quality": "Qualité",
  "export.quality.draft": "Brouillon",
  "export.width": "Largeur",
  "export.height": "Hauteur",
  "export.camera": "Caméra",
  "export.activeCamera": "Caméra active",
  "export.viewportCamera": "Caméra de la vue 3D",
  "export.options": "Options de rendu",
  "export.includePost": "Inclure le post-traitement",
  "export.includeVfx": "Inclure les superpositions VFX cinématiques",
  "export.includeBars": "Inclure les bandes cinématiques",
  "export.transparent": "Arrière-plan PNG transparent",
  "export.includeAudio": "Inclure l’audio lorsque le format sélectionné le permet",
  "export.ffmpeg": "FFmpeg pour bureau",
  "export.ffmpegPath": "Exécutable ou chemin FFmpeg",
  "export.outputDirectory": "Dossier de sortie natif",
  "export.encodingTarget": "Cible d’encodage",
  "export.encoding.small": "Fichier plus petit",
  "export.encoding.balanced": "Équilibré",
  "export.encoding.high": "Haute qualité",
  "export.overwrite": "Écraser la sortie existante",
  "export.preset.draft720": "Aperçu brouillon 720p",
  "export.preset.youtube1080": "YouTube 1080p",
  "export.preset.youtube1440": "YouTube 1440p",
  "export.preset.vertical": "Short vertical 1080x1920",
  "export.preset.cinematic": "Cinématique 2,35:1 1080p",
  "export.preset.square": "Carré 1080",
  "export.preset.pngHigh": "Séquence PNG haute qualité",
  "export.preset.pngTransparent": "Séquence PNG transparente",
  "export.preset.webmSmall": "WebM de petite taille",
  "export.detectFfmpeg": "Détecter FFmpeg",
  "export.validation": "Validation",
  "export.webmUnavailable": "WebM n’est pas disponible dans cet environnement.",
  "export.audioUnavailable": "Le mixage audio n’est pas disponible dans cet environnement.",
  "export.ffmpegAvailable": "FFmpeg natif est disponible.",
  "export.ffmpegUnavailable": "FFmpeg natif est indisponible ou n’a pas été détecté.",
  "export.issue.cameraMissing": "Aucune caméra active ou d’export n’est disponible.",
  "export.issue.frameOrder": "L’image de début doit précéder ou être égale à l’image de fin.",
  "export.issue.frameEmpty": "La plage doit contenir au moins une image.",
  "export.issue.endAfterProject": "L’image de fin dépasse la durée du projet ; le dernier état de la scène sera conservé.",
  "export.issue.directoryMissing": "Choisissez un dossier de sortie FFmpeg avant de lancer un export natif.",
  "export.issue.nameMissing": "Un nom de sortie est requis.",
  "export.issue.webmUnsupported": "L’export WebM requiert la prise en charge des bitmaps, de MediaRecorder et de la capture canvas.",
  "export.issue.webmVideoOnly": "Le WebM du navigateur contient uniquement la vidéo ; exportez le WAV séparément ou utilisez le MP4 natif pour multiplexer l’audio.",
  "export.issue.wavUnsupported": "Le mixage WAV requiert la prise en charge d’OfflineAudioContext par le navigateur.",
  "export.issue.muxUnsupported": "Le multiplexage audio de la vidéo native requiert le mixage WAV.",
  "export.issue.mp3MixdownUnsupported": "L’export MP3 requiert le mixage WAV avant l’encodage FFmpeg.",
  "export.issue.mp3NativeOnly": "L’export MP3 requiert FFmpeg ; le mode navigateur ne le simule pas.",
  "export.issue.resolutionHigh": "La résolution dépasse la 4K et peut ralentir l’export dans le navigateur.",
  "export.issue.sizeHigh": "La taille de sortie estimée dépasse 2 Go.",
  "export.issue.postDisabled": "Le post-traitement est demandé mais désactivé dans les paramètres du projet.",
  "export.issue.vfxEmpty": "L’export VFX est activé mais le projet ne contient aucune instance d’effet.",
  "export.issue.ffmpegRequired": "{format} requiert la prise en charge native de FFmpeg.",
  "export.issue.assetsMissing": "{count} ressources suivies sont manquantes ou invalides.",
  "export.issue.unmapped": "Un diagnostic d’export n’a pas pu être présenté de manière sûre.",
  "export.runPackage": "Lancer ou empaqueter",
  "export.addQueue": "Ajouter à la file",
  "export.pngFrame": "Image PNG",
  "export.pngZip": "ZIP PNG",
  "export.cancel": "Annuler",
  "export.savePackage": "Enregistrer en .minemotion",
  "export.exportLegacy": "Exporter en .mmsproj",
  "export.trackedAssets.one": "{count} ressource suivie",
  "export.trackedAssets.other": "{count} ressources suivies",
  "export.missingAssets.one": "{count} manquante",
  "export.missingAssets.other": "{count} manquantes",
  "export.packageWarnings.one": "{count} avertissement de paquet",
  "export.packageWarnings.other": "{count} avertissements de paquet",
  "export.renderQueue": "File de rendu",
  "export.check.camera": "Caméra d’export",
  "export.check.frameRange": "Plage d’images",
  "export.check.format": "Prise en charge du format",
  "export.check.assets": "Disponibilité des ressources",
  "export.check.audio": "Compatibilité audio",
  "export.check.frameCount": "Nombre d’images",
  "export.check.size": "Taille estimée",
  "export.check.post": "État du post-traitement",
  "export.check.effects": "État des VFX",
  "export.frames.one": "{count} image",
  "export.frames.other": "{count} images",
  "export.seconds": "{count} secondes",
  "export.approx": "Environ {size}",
  "export.noRunning": "Aucun export en cours.",
  "export.status.idle": "Inactif",
  "export.status.preparing": "Préparation",
  "export.status.rendering": "Rendu",
  "export.status.encoding": "Encodage",
  "export.status.complete": "Terminé",
  "export.status.cancelled": "Annulé",
  "export.status.error": "Erreur",
  "export.progress.idle": "Aucun export en cours.",
  "export.progress.preparing": "Préparation de l’export validé.",
  "export.progress.rendering": "Rendu de la plage d’images sélectionnée.",
  "export.progress.encoding": "Encodage de la sortie rendue.",
  "export.progress.complete": "Export terminé.",
  "export.progress.cancelled": "Export annulé.",
  "export.progress.error": "L’export s’est arrêté avec une erreur.",
  "export.runtimeFailed": "Le moteur d’export a échoué. Vérifiez le format sélectionné et les capacités de l’environnement.",
  "queue.jobs.one": "{count} tâche",
  "queue.jobs.other": "{count} tâches",
  "queue.clearFinished": "Effacer les tâches terminées",
  "queue.empty": "La file de rendu est vide.",
  "queue.run": "Lancer la tâche de rendu",
  "queue.remove": "Retirer la tâche de rendu",
  "timeline.editorAria": "Vue de l’éditeur d’animation",
  "timeline.timeline": "Timeline",
  "timeline.dopesheet": "Feuille d’exposition",
  "timeline.graph": "Courbes",
  "timeline.nla": "NLA",
  "timeline.goStart": "Aller au début",
  "timeline.previousKey": "Image clé précédente",
  "timeline.nextKey": "Image clé suivante",
  "timeline.goEnd": "Aller à la fin",
  "timeline.frame": "Image",
  "timeline.fps": "IPS",
  "timeline.addMarker": "Ajouter un marqueur",
  "timeline.addKey": "Ajouter une clé",
  "timeline.markerPrompt": "Nom du marqueur",
  "timeline.markerDefault": "Marqueur {count}",
  "timeline.clipPrompt": "Nom du clip d’animation",
  "timeline.clipDefault": "Clip réutilisable",
  "timeline.copyKeys": "Copier les images clés sélectionnées",
  "timeline.pasteKeys": "Coller les images clés à la tête de lecture",
  "timeline.duplicateKeys": "Dupliquer les images clés sélectionnées",
  "timeline.deleteKeys": "Supprimer les images clés sélectionnées",
  "timeline.snap": "Magnétisme",
  "timeline.step": "Pas",
  "timeline.interpolationAria": "Interpolation des images clés sélectionnées",
  "timeline.interpolation.constant": "Constante",
  "timeline.interpolation.linear": "Linéaire",
  "timeline.interpolation.easeIn": "Accélération",
  "timeline.interpolation.easeOut": "Décélération",
  "timeline.interpolation.easeInOut": "Accélération et décélération",
  "timeline.interpolation.bezier": "Bézier",
  "timeline.saveClip": "Enregistrer le clip",
  "timeline.clipAria": "Clip d’animation réutilisable",
  "timeline.clips": "Clips d’animation",
  "timeline.applyClip": "Appliquer le clip",
  "timeline.addNla": "Ajouter à la NLA",
  "timeline.effectSelected": "FX : {name}",
  "timeline.moveEffectEarlier": "Déplacer l’effet sélectionné plus tôt",
  "timeline.moveEffectLater": "Déplacer l’effet sélectionné plus tard",
  "timeline.moveEffectPlayhead": "Déplacer l’effet sélectionné à la tête de lecture",
  "timeline.moveAt": "Déplacer @",
  "timeline.trimStart": "Rogner le début de l’effet sélectionné à la tête de lecture",
  "timeline.trimEnd": "Rogner la fin de l’effet sélectionné à la tête de lecture",
  "timeline.trimLeft": "Rogner G",
  "timeline.trimRight": "Rogner D",
  "timeline.duplicateEffect": "Dupliquer l’effet sélectionné",
  "timeline.copyEffect": "Copier l’effet sélectionné",
  "timeline.pasteEffect": "Coller l’effet copié à la tête de lecture",
  "timeline.disableEffect": "Désactiver l’effet sélectionné",
  "timeline.enableEffect": "Activer l’effet sélectionné",
  "timeline.disableFx": "Désactiver le FX",
  "timeline.enableFx": "Activer le FX",
  "timeline.priorityEarlier": "Avancer l’effet sélectionné dans l’ordre de priorité persistant",
  "timeline.priorityLater": "Reculer l’effet sélectionné dans l’ordre de priorité persistant",
  "timeline.priorityMinus": "Priorité -",
  "timeline.priorityPlus": "Priorité +",
  "timeline.copied": "Copié : {name}",
  "timeline.summary": "{selected} sélectionnées / {markers} marqueurs / {clips} clips",
  "timeline.scrubberAria": "Curseur de la timeline",
  "timeline.frameTitle": "Image {frame}",
  "timeline.nlaEmpty": "Enregistrez un clip, sélectionnez-le, puis ajoutez-le à la NLA.",
  "timeline.missingClip": "Clip manquant",
  "timeline.missing": "Manquant",
  "timeline.laneAria": "Piste {label}",
  "timeline.disabledSuffix": "désactivé",
  "timeline.dragMove": "{title}. Faites glisser pour déplacer.",
  "timeline.trimItemStart": "Rogner le début de {name}",
  "timeline.trimItemEnd": "Rogner la fin de {name}",
  "timeline.dragTrimStart": "Faites glisser pour rogner le début de l’effet",
  "timeline.dragTrimEnd": "Faites glisser pour rogner la fin de l’effet",
  "history.moveKeys": "Déplacer les images clés",
  "history.addMarker": "Ajouter un marqueur à la timeline",
  "history.saveClip": "Enregistrer un clip d’animation",
  "history.applyClip": "Appliquer un clip d’animation",
  "history.addNla": "Ajouter un clip NLA",
  "history.pasteKeys": "Coller les images clés",
  "history.duplicateKeys": "Dupliquer les images clés",
  "history.deleteKeys": "Supprimer les images clés",
  "history.compressKeys": "Compresser le rythme des images clés",
  "history.expandKeys": "Étendre le rythme des images clés",
  "history.setInterpolation": "Définir l’interpolation des images clés",
  "history.setGraphInterpolation": "Définir l’interpolation des courbes",
  "history.toggleNla": "Activer ou désactiver le clip NLA",
  "inspector.title": "Inspecteur",
  "inspector.sky": "Ciel",
  "inspector.preset": "Préréglage",
  "inspector.customColor": "Couleur personnalisée",
  "inspector.selectPrompt": "Sélectionnez un objet pour modifier sa transformation.",
  "inspector.character": "Personnage",
  "inspector.rig": "Rig",
  "inspector.boneId": "Identifiant de l’os",
  "inspector.boneRotation": "Rotation de l’os",
  "inspector.addBoneKey": "Ajouter une image clé à l’os",
  "inspector.post": "Post-traitement",
  "inspector.enablePost": "Activer le post-traitement",
  "inspector.bloom": "Halo lumineux",
  "inspector.vignette": "Vignettage",
  "inspector.saturation": "Saturation",
  "inspector.contrast": "Contraste",
  "inspector.grain": "Grain",
  "inspector.pixelate": "Pixellisation",
  "inspector.type": "Type",
  "inspector.start": "Début",
  "inspector.duration": "Durée",
  "inspector.position": "Position",
  "inspector.rotation": "Rotation",
  "inspector.scale": "Échelle",
  "inspector.deleteEffect": "Supprimer l’effet",
  "inspector.invalidParameter": "La valeur du paramètre est invalide.",
  "inspector.parametersUnavailable": "Les contrôles de paramètres ne sont pas disponibles.",
  "inspector.parameterNote": "Les valeurs proviennent du schéma de l’effet. Les images clés de paramètres nécessitent le schéma 10.",
  "inspector.legacyParameters": "Paramètres historiques conservés ({count})",
  "inspector.colorPicker": "Sélecteur de couleur pour {name}",
  "inspector.invalidLegacy": "Valeur historique invalide : {value}",
  "inspector.minimum": "min. {value}",
  "inspector.maximum": "max. {value}",
  "inspector.stepValue": "pas {value}",
  "inspector.defaultValue": "Valeur par défaut : {value}",
  "inspector.runtime.live": "Aperçu en direct",
  "inspector.runtime.export": "Export hors ligne uniquement",
  "inspector.runtime.stored": "Stocké uniquement (prise en charge du rendu à venir)",
  "inspector.keyframesSchema10": "Images clés indisponibles avant le schéma 10.",
  "inspector.storedLegacy": "Valeur historique stockée : {value}",
  "inspector.restoreDefault": "Restaurer la valeur valide par défaut",
  "inspector.world": "Monde",
  "inspector.source": "Source",
  "inspector.level": "Niveau",
  "inspector.found": "trouvé",
  "inspector.missing": "manquant",
  "inspector.spawn": "Point d’apparition",
  "inspector.dimension": "Dimension",
  "inspector.chunks": "Chunks",
  "inspector.blocks": "Blocs",
  "inspector.unknown": "Inconnus",
  "inspector.regionFiles.one": "{count} fichier de région",
  "inspector.regionFiles.other": "{count} fichiers de région",
  "inspector.demoTerrain": "Le terrain de démonstration reste actif jusqu’à l’analyse d’un dossier de monde Minecraft.",
  "inspector.name": "Nom",
  "inspector.visible": "Visible",
  "inspector.hidden": "Masqué",
  "inspector.locked": "Verrouillé",
  "inspector.unlocked": "Déverrouillé",
  "inspector.addKeyframe": "Ajouter une image clé",
  "inspector.lookThrough": "Regarder à travers",
  "inspector.cameraPresets": "Préréglages de caméra",
  "inspector.addCameraPreset": "Ajouter un préréglage de caméra",
  "inspector.poseLibrary": "Bibliothèque de poses",
  "inspector.applyPose": "Appliquer la pose",
  "inspector.animationPresets": "Préréglages d’animation",
  "inspector.applyAnimation": "Appliquer le préréglage d’animation",
  "inspector.rigSkin": "Rig et skin",
  "inspector.rigPreset": "Préréglage de rig",
  "inspector.placeholder": "provisoire",
  "inspector.bones": "Os",
  "inspector.arms": "Bras",
  "inspector.skin": "Skin",
  "inspector.resolution": "Résolution",
  "inspector.model": "Modèle",
  "inspector.valid": "Valide",
  "inspector.yes": "oui",
  "inspector.no": "non",
  "inspector.fallbackColors": "couleurs de remplacement",
  "inspector.presetAction": "{action} : {name}",
  "lighting.title": "Studio d’éclairage",
  "lighting.closeAria": "Fermer le studio d’éclairage",
  "lighting.moods": "Préréglages d’ambiance",
  "lighting.sunAmbient": "Soleil et lumière ambiante",
  "lighting.sunIntensity": "Intensité du soleil",
  "lighting.ambientIntensity": "Intensité ambiante",
  "lighting.sunColor": "Couleur du soleil",
  "lighting.ambientColor": "Couleur ambiante",
  "lighting.sunDirection": "Direction du soleil",
  "lighting.shadows": "Ombres",
  "lighting.atmosphere": "Atmosphère",
  "lighting.fogColor": "Couleur du brouillard",
  "lighting.fogDensity": "Densité du brouillard",
  "lighting.timeOfDay": "Heure de la journée",
  "lighting.animateTime": "Animer l’heure de la journée",
  "lighting.dayLength": "Durée du jour (images)",
  "lighting.keyframeAt": "Image clé à {frame}",
  "lighting.environmentKeys.one": "{count} clé d’environnement",
  "lighting.environmentKeys.other": "{count} clés d’environnement",
  "lighting.shaderPost": "Shader et post-traitement",
  "lighting.enablePost": "Activer le post-traitement",
  "lighting.bloom": "Halo lumineux",
  "lighting.vignette": "Vignettage",
  "lighting.grain": "Grain",
  "lighting.chromatic": "Aberration chromatique",
  "lighting.exposure": "Exposition",
  "lighting.contrast": "Contraste",
  "lighting.materials": "Matériaux Minecraft",
  "lighting.filtering": "Filtrage des textures",
  "lighting.nearest": "Au plus proche (Minecraft)",
  "lighting.linear": "Linéaire",
  "lighting.defaultMaterial": "Matériau par défaut",
  "lighting.biomeTint": "Teinte de couleur du biome",
  "lighting.biomePreset": "Préréglage de teinte du biome",
  "lighting.grass": "Herbe",
  "lighting.foliage": "Feuillage",
  "lighting.water": "Eau",
  "lighting.resourcePacks": "Packs de ressources",
  "lighting.importZip": "Importer un ZIP",
  "lighting.importFolder": "Importer un dossier",
  "lighting.resetTextures": "Réinitialiser les textures",
  "lighting.noResourcePack": "Aucun pack de ressources importé.",
  "lighting.packSummary": "pack_format {format} / {count} textures de blocs / {source}",
  "lighting.apply": "Appliquer",
  "lighting.removePack": "Retirer {name}",
  "dopesheet.empty": "Ajoutez des images clés pour remplir la feuille d’exposition.",
  "dopesheet.ariaLabel": "Feuille d’exposition de l’animation",
  "graph.empty": "Sélectionnez une image clé pour examiner ses courbes de propriété.",
  "graph.interpolation": "Interpolation",
  "graph.bezierPlaceholder": "Bézier (provisoire)",
  "graph.curvesAria": "Courbes d’animation de {property}",
  "app.ready": "Prêt. Les systèmes professionnels d’animation, de packs de ressources et d’éclairage sont chargés.",
  "app.confirmAutosave": "Une sauvegarde automatique MineMotion a été trouvée dans ce navigateur. La restaurer ?",
  "app.autosaveBackupRestored": "La sauvegarde automatique principale était invalide ; la copie de secours conservée a été restaurée.",
  "app.autosaveRestored": "Projet restauré depuis la sauvegarde automatique du navigateur.",
  "app.recoveryRetained": "{message} Les données de récupération stockées ont été conservées.",
  "app.recoveryFailed": "La récupération automatique a échoué ; les données de récupération stockées ont été conservées.",
  "app.autosaved": "{name} sauvegardé automatiquement dans le navigateur.",
  "app.autosaveFailedDetail": "Échec de la sauvegarde automatique : {message}",
  "app.autosaveFailed": "Échec de la sauvegarde automatique.",
  "app.confirmDiscard": "Le projet actuel contient des modifications non enregistrées. Continuer ?",
  "app.newProject": "Nouveau projet créé.",
  "app.templateLoaded": "Modèle chargé : {name}.",
  "app.projectSaved": "Projet enregistré sous {filename}.",
  "app.legacyExported": "Projet au schéma historique 9 exporté sous {filename}.",
  "app.legacyVfxUnsupported": "Le projet contient des données VFX natives que le schéma 9 ne peut pas représenter.",
  "app.projectLoaded": "Projet {name} chargé.",
  "app.projectLoadFailed": "Impossible de charger le projet.",
  "app.worldScanning": "Analyse du dossier du monde Minecraft.",
  "app.worldScanned": "{name} analysé.",
  "app.worldScanComplete": "Analyse du monde terminée : {name}, {dimensions} fichiers de région.",
  "app.worldScanFailed": "Impossible d’analyser le dossier du monde.",
  "app.chooseWorld": "Choisissez un dossier de monde Minecraft avant d’importer des chunks.",
  "app.worldPreparing": "Préparation de l’import des chunks.",
  "app.worldImported": "{chunks} chunks et {blocks} blocs importés depuis {name}.",
  "app.worldImportFailed": "Échec de l’import des chunks Minecraft.",
  "app.worldCancel": "Annulation de l’import du monde demandée.",
  "app.worldFocused": "Vue 3D cadrée sur le monde importé.",
  "app.worldUnloaded": "Monde importé déchargé ; terrain de démonstration restauré.",
  "app.addedEntity": "{name} ajouté.",
  "app.objImportedWarning": "OBJ importé avec un avertissement : {warning}",
  "app.objImportedWarnings": "OBJ {name} importé avec {count} avertissements techniques.",
  "app.objImported": "OBJ {name} importé.",
  "app.objFailed": "Impossible d’importer l’OBJ.",
  "app.selectCharacterSkin": "Sélectionnez un personnage avant d’importer un skin.",
  "app.skinImported": "Skin {name} importé ({width}x{height}, {model}).",
  "app.skinInvalid": "Le skin {name} a été importé mais il est invalide ; les couleurs de remplacement restent actives.",
  "app.skinFailed": "Impossible d’importer le skin.",
  "app.skinReset": "Skin réinitialisé aux couleurs Minecraft de remplacement.",
  "app.blockbenchImported": "Modèle Blockbench {name} importé : {cubes} cubes, {groups} groupes.",
  "app.blockbenchFailed": "Impossible d’importer le modèle Blockbench.",
  "app.entityLocked": "{name} est verrouillé.",
  "app.effectFinalFrame": "Placez-vous avant la dernière image du projet pour ajouter un effet.",
  "app.effectAddFailed": "Impossible d’ajouter l’effet cinématique.",
  "app.effectAdded": "Effet {name} ajouté à l’image {frame}.",
  "app.customVfxUnavailable": "Le paquet VFX personnalisé {id} est manquant ou désactivé.",
  "app.customVfxAddFailed": "Impossible d’ajouter le VFX personnalisé.",
  "app.vfxRegistryWarnings": "{count} entrées de packs VFX installés n’ont pas pu être chargées en toute sécurité.",
  "app.customVfxAdded": "VFX personnalisé {name} ajouté à l’image {frame}.",
  "app.effectEditFailed": "Échec de la modification de la timeline d’effets.",
  "app.effectUnchanged": "La timeline d’effets possède déjà cette valeur.",
  "app.postPreset": "Préréglage de post-traitement appliqué : {name}.",
  "app.postUpdated": "Post-traitement mis à jour.",
  "app.previewToggled": "Aperçu du rendu activé ou désactivé.",
  "app.barsToggled": "Bandes cinématiques activées ou désactivées.",
  "app.ffmpegChanged": "L’exécutable FFmpeg a changé. Relancez la détection.",
  "app.ffmpegDetecting": "Détection de FFmpeg…",
  "app.jobAdded": "{name} ajouté à la file de rendu.",
  "app.exportInvalid": "Les paramètres d’export sont invalides.",
  "app.captureFrame": "Capture de l’image courante de la vue 3D.",
  "app.exported": "{filename} exporté.",
  "app.pngFailed": "Échec de l’export PNG.",
  "app.sequencePreparing": "Préparation de l’export de la séquence PNG.",
  "app.sequenceFailed": "Échec de l’export de la séquence PNG.",
  "app.webmRecording": "Enregistrement du canevas de la vue 3D en WebM.",
  "app.recordingFrame": "Enregistrement de l’image {frame} sur {total}.",
  "app.exportedSize": "{filename} exporté en {width}x{height}.",
  "app.webmFailed": "Échec de l’export WebM.",
  "app.wavMixing": "Mixage de l’audio du projet en WAV.",
  "app.wavFailed": "Échec de l’export WAV.",
  "app.exportCancel": "Annulation de l’export demandée.",
  "app.sfxUnsupported": "Type de fichier sonore non pris en charge. Utilisez un fichier wav, mp3 ou ogg.",
  "app.sfxImported": "Effet sonore {name} importé.",
  "app.sfxFailed": "Impossible d’importer l’effet sonore.",
  "app.sfxAdded": "Effet sonore provisoire {name} ajouté.",
  "app.selectDuplicate": "Sélectionnez un objet avant de le dupliquer.",
  "app.duplicated": "{name} dupliqué.",
  "app.boneUpdated": "Rotation de {bone} mise à jour.",
  "app.boneKey": "Image clé d’os ajoutée pour {bone} à l’image {frame}.",
  "app.poseReset": "Pose du rig réinitialisée.",
  "app.poseMirrored": "Pose du rig inversée gauche/droite.",
  "app.posePrompt": "Nom de la pose",
  "app.poseDefault": "Pose de {name}",
  "app.poseSaved": "Pose {name} enregistrée.",
  "app.rigChanged": "Préréglage de rig remplacé par {name}.",
  "app.selectDelete": "Sélectionnez un objet avant de le supprimer.",
  "app.deleted": "{name} supprimé.",
  "app.selectKeyframe": "Sélectionnez un personnage, une caméra, un éclairage ou un OBJ avant d’ajouter une image clé.",
  "app.notKeyframeable": "L’objet sélectionné ne peut pas recevoir d’image clé.",
  "app.transformKey": "Image clé de transformation ajoutée pour {name} à l’image {frame}.",
  "app.skyChanged": "Préréglage de ciel défini sur {preset}.",
  "app.lightingMood": "Ambiance lumineuse appliquée : {name}.",
  "app.lightingUpdated": "Éclairage mis à jour.",
  "app.materialsUpdated": "Paramètres des matériaux Minecraft mis à jour.",
  "app.resourcePackImported": "Pack de ressources {name} importé : {count} textures de blocs.",
  "app.resourceZipFailed": "Impossible d’importer le pack de ressources ZIP.",
  "app.resourceFolderFailed": "Impossible d’importer le dossier du pack de ressources.",
  "app.resourceApplied": "Pack de ressources appliqué.",
  "app.resourceReset": "Textures du pack de ressources réinitialisées.",
  "app.resourceRemoved": "Pack de ressources retiré.",
  "app.environmentKey": "Image clé d’environnement ajoutée à l’image {frame}.",
  "app.projectSettingsUpdated": "Paramètres du projet mis à jour.",
  "app.selectCamera": "Sélectionnez d’abord une caméra de la scène.",
  "app.cameraMoved": "Vue 3D déplacée à la position de la caméra sélectionnée.",
  "app.cameraReset": "Caméra de la vue 3D réinitialisée sur la première caméra de la scène.",
  "app.cameraPreset": "Préréglage de caméra appliqué : {name}.",
  "app.poseApplied": "Pose appliquée : {name}.",
  "app.animationPreset": "Préréglage d’animation appliqué : {name}.",
  "app.nothingUndo": "Rien à annuler.",
  "app.undo": "Annulation effectuée.",
  "app.nothingRedo": "Rien à rétablir.",
  "app.redo": "Rétablissement effectué.",
  "app.pluginState": "Extension {id} : {state}.",
  "status.selected": "Sélection : {name}",
  "status.frame": "Image : {frame}",
  "status.fps": "IPS : {fps}",
  "status.unsaved": "Non enregistré",
  "status.saved": "Enregistré",
  "status.post": "Post-traitement : {preset}",
  "status.lighting": "Éclairage : {preset}",
  "status.effects": "FX : {count}",
  "status.audio": "SFX : {count}",
  "status.export": "Export : {width}x{height}",
  "status.renderPreview": "Aperçu du rendu",
  "status.viewport": "Vue 3D",
  "status.world": "Monde : {name}",
  "status.worldDemo": "Monde : démo",
  "status.character": "Personnage",
  "viewport.ariaLabel": "Vue 3D",
  "viewport.perspective": "Perspective",
  "viewport.activeCamera": "Caméra active : {name}",
  "viewport.orbit": "Orbite : glisser",
  "viewport.pan": "Déplacement : glisser avec le bouton droit",
  "viewport.zoom": "Zoom : molette",
  "viewport.importedChunks.one": "{count} chunk importé",
  "viewport.importedChunks.other": "{count} chunks importés",
  "format.minute.short": "min",
  "format.second.short": "s",
  "format.effects.one": "{count} effet",
  "format.effects.other": "{count} effets"
} as const satisfies TranslationCatalog);
